In [1]:
import os
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

# Path to your Excel training data
TRAINING_XLSX = "data/hea_FeCoNiCrV_k_cte_calphad_modeled_data.xlsx"

# Input columns must match the component labels / order used in DesignSpace
INPUT_COLS = ["Fe", "Co", "Ni", "Cr", "V"]

# Target columns in your Excel sheet
TARGET_COLS = [
    "CTE (x 10^(-6) 1/K)",
    "K (W/(mK))",
]

# Where to save the optimized models, scalers, plots, and optimization studies and results
OUTPUT_DIR = "ground_truth_models/FeCoNiCrV_Min_CTE_Max_K"
os.makedirs(OUTPUT_DIR, exist_ok=True)

MODELS_PATH = os.path.join(OUTPUT_DIR, "models")
PLOTS_PATH = os.path.join(OUTPUT_DIR, "plots")
STUDIES_PATH = os.path.join(OUTPUT_DIR, "studies")
RESULTS_PATH = OUTPUT_DIR

In [2]:
# If your data is on a specific sheet, pass sheet_name="Sheet1" (or the right name).
df = pd.read_excel(TRAINING_XLSX)  # , sheet_name="Sheet1"
df.head()

    Fe   Co   Ni    Cr     V  CTE (1/K)  K (W/(mK))        K/CTE
0  0.1  0.1  0.1  0.30  0.40   0.000009    7.447543  819403.1824
1  0.1  0.1  0.1  0.32  0.38   0.000009    7.715431  852620.8795
2  0.1  0.1  0.1  0.34  0.36   0.000009    7.956606  882843.4959
3  0.1  0.1  0.1  0.36  0.34   0.000009    8.171040  910002.9011
4  0.1  0.1  0.1  0.38  0.32   0.000009    8.359425  934130.3152

In [3]:
# Convert CTE
df['CTE (x 10^(-6) 1/K)'] = df['CTE (1/K)'] * 1e6
df.head()

,Fe,Co,Ni,Cr,V,CTE (1/K),K (W/(mK)),K/CTE,CTE (x 10^(-6) 1/K)
0,0.1,0.1,0.1,0.30,0.40,0.000009,7.447543,819403.1824,9.09
1,0.1,0.1,0.1,0.32,0.38,0.000009,7.715431,852620.8795,9.05
2,0.1,0.1,0.1,0.34,0.36,0.000009,7.956606,882843.4959,9.01
3,0.1,0.1,0.1,0.36,0.34,0.000009,8.171040,910002.9011,8.98
4,0.1,0.1,0.1,0.38,0.32,0.000009,8.359425,934130.3152,8.95

In [4]:
# Extract inputs (X) and targets (y)
X_raw = df[INPUT_COLS]
y_raw = df[TARGET_COLS]

print("X_raw shape:", X_raw.shape)
print("y_raw shape:", y_raw.shape)

X_raw shape: (17852, 5)
y_raw shape: (17852, 2)

In [5]:
# Define models
models = {
    "Linear": LinearRegression(),
    "RFR": RandomForestRegressor()
}

In [6]:
# Define hyperparameter spaces for optimization
param_spaces = {
    "RFR": {
        "n_estimators": ('int', 10, 150),   # Number of trees
        "max_depth": ('int', 10, 150),         # Maximum depth of trees
        "min_samples_split": ('int', 2, 20), # Minimum number of samples required to split an internal node
        "min_samples_leaf": ('int', 1, 20)   # Minimum number of samples required to be at a leaf node
    }
}

In [7]:
# Import the run_workflow function from workflow.py
from core.armote_multi_output import run_workflow

# Define output labels
output_labels = ['CTE (x 10^(-6) 1/K)', 'K (W/(m K))']

# Define the folder dictionary
folder_dict = {
    'models': MODELS_PATH,
    'plots': PLOTS_PATH,
    'studies': STUDIES_PATH,
    'results': RESULTS_PATH
    }

# Run the workflow
results_df = run_workflow(X_raw, y_raw, models, param_spaces, output_labels=output_labels, folder_dict=folder_dict)

# Display the results DataFrame
print(results_df)

Setting up output folders...
✓ Models folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\FeCoNiCrV_Min_CTE_Max_K\models
✓ Plots folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\FeCoNiCrV_Min_CTE_Max_K\plots
✓ Studies folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\FeCoNiCrV_Min_CTE_Max_K\studies
✓ Results folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\FeCoNiCrV_Min_CTE_Max_K

Initializing multi-output workflow...
NOTE: Optimization uses SCALED data for fair comparison across outputs
      Reporting includes normalized metrics (RMSE/std) for fair comparison

Fitting and saving data scalers...
  Scalers saved to: ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\models

--- Starting Workflow for: Linear ---
  Checking multi-output support for LinearRegression...
  → LinearRegression supports multi-output natively.
  No hyperparameters defined. Training model with default settings.
  Retraining the final model with the best hyperparameters...
  Final model training complete in 0.002 seconds.
  Best model saved to: ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\models\Linear_best_model.pkl

[I 2026-02-03 11:27:12,465] A new study created in memory with name: no-name-75daffe6-7597-4ae5-980a-92db03578e76

  Y-Y plot saved to: ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\plots\Linear_yy_plot.png

--- Starting Workflow for: RFR ---
  Checking multi-output support for RandomForestRegressor...
  → RandomForestRegressor supports multi-output natively.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-02-03 11:27:23,062] Trial 0 finished with values: [0.08248021744915374, 0.9174941533146045] and parameters: {'n_estimators': 122, 'max_depth': 94, 'min_samples_split': 15, 'min_samples_leaf': 10}.
[I 2026-02-03 11:27:25,476] Trial 1 finished with values: [0.0916340544314867, 0.9083870794319908] and parameters: {'n_estimators': 81, 'max_depth': 31, 'min_samples_split': 4, 'min_samples_leaf': 18}.
[I 2026-02-03 11:27:27,343] Trial 5 finished with values: [0.09133589588872368, 0.908703543195853] and parameters: {'n_estimators': 22, 'max_depth': 103, 'min_samples_split': 14, 'min_samples_leaf': 3}.
[I 2026-02-03 11:27:28,816] Trial 6 finished with values: [0.09171792225363642, 0.9083159222055655] and parameters: {'n_estimators': 51, 'max_depth': 33, 'min_samples_split': 18, 'min_samples_leaf': 4}.
[I 2026-02-03 11:27:28,976] Trial 8 finished with values: [0.0913447252090162, 0.908699049335105] and parameters: {'n_estimators': 41, 'max_depth': 67, 'min_samples_split': 16, 'min_samples_leaf': 1}.
[I 2026-02-03 11:27:29,609] Trial 3 finished with values: [0.08637652309173412, 0.9135856854890955] and parameters: {'n_estimators': 70, 'max_depth': 23, 'min_samples_split': 17, 'min_samples_leaf': 5}.
[I 2026-02-03 11:27:31,512] Trial 9 finished with values: [0.09127048161643911, 0.9084921663213148] and parameters: {'n_estimators': 35, 'max_depth': 57, 'min_samples_split': 8, 'min_samples_leaf': 13}.
[I 2026-02-03 11:27:31,601] Trial 15 finished with values: [0.10215182440655524, 0.8978102461272103] and parameters: {'n_estimators': 103, 'max_depth': 26, 'min_samples_split': 18, 'min_samples_leaf': 17}.
[I 2026-02-03 11:27:31,703] Trial 4 finished with values: [0.0932771336299438, 0.9063900837470588] and parameters: {'n_estimators': 54, 'max_depth': 109, 'min_samples_split': 16, 'min_samples_leaf': 9}.
[I 2026-02-03 11:27:32,137] Trial 12 finished with values: [0.10216952308526968, 0.8978081477157612] and parameters: {'n_estimators': 19, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 3}.
[I 2026-02-03 11:27:32,342] Trial 10 finished with values: [0.09572473959787339, 0.9042409525465154] and parameters: {'n_estimators': 74, 'max_depth': 104, 'min_samples_split': 17, 'min_samples_leaf': 4}.
[I 2026-02-03 11:27:32,827] Trial 13 finished with values: [0.10201101444218379, 0.8979751673936119] and parameters: {'n_estimators': 143, 'max_depth': 142, 'min_samples_split': 18, 'min_samples_leaf': 5}.
[I 2026-02-03 11:27:33,947] Trial 11 finished with values: [0.10200390551502517, 0.8979708842476963] and parameters: {'n_estimators': 102, 'max_depth': 88, 'min_samples_split': 16, 'min_samples_leaf': 13}.
[I 2026-02-03 11:27:34,024] Trial 7 finished with values: [0.09224744434944146, 0.9077946811372524] and parameters: {'n_estimators': 18, 'max_depth': 27, 'min_samples_split': 11, 'min_samples_leaf': 2}.
[I 2026-02-03 11:27:34,838] Trial 2 finished with values: [0.08882645768487134, 0.91114500002933] and parameters: {'n_estimators': 29, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 6}.
[I 2026-02-03 11:27:34,928] Trial 18 finished with values: [0.09086880185493029, 0.9091070117532825] and parameters: {'n_estimators': 32, 'max_depth': 70, 'min_samples_split': 5, 'min_samples_leaf': 13}.
[I 2026-02-03 11:27:34,975] Trial 17 finished with values: [0.1021474817651999, 0.8978284889520204] and parameters: {'n_estimators': 47, 'max_depth': 103, 'min_samples_split': 17, 'min_samples_leaf': 17}.
[I 2026-02-03 11:27:36,098] Trial 16 finished with values: [0.07772067046536346, 0.9222609832460948] and parameters: {'n_estimators': 79, 'max_depth': 102, 'min_samples_split': 9, 'min_samples_leaf': 9}.
[I 2026-02-03 11:27:36,443] Trial 19 finished with values: [0.06175993390061065, 0.9382382067813071] and parameters: {'n_estimators': 50, 'max_depth': 59, 'min_samples_split': 4, 'min_samples_leaf': 5}.
[I 2026-02-03 11:27:37,569] Trial 14 finished with values: [0.10154054428486803, 0.8984007542905331] and parameters: {'n_estimators': 19, 'max_depth': 100, 'min_samples_split': 9, 'min_samples_leaf': 9}.
[I 2026-02-03 11:27:39,162] Trial 20 finished with values: [0.049661829364503696, 0.9503410412060059] and parameters: {'n_estimators': 123, 'max_depth': 33, 'min_samples_split': 6, 'min_samples_leaf': 2}.
[I 2026-02-03 11:27:40,655] Trial 22 finished with values: [0.06995908681814078, 0.9300417192453991] and parameters: {'n_estimators': 110, 'max_depth': 35, 'min_samples_split': 15, 'min_samples_leaf': 7}.
[I 2026-02-03 11:27:41,222] Trial 24 finished with values: [0.09155922097973598, 0.9083981341605449] and parameters: {'n_estimators': 80, 'max_depth': 55, 'min_samples_split': 10, 'min_samples_leaf': 13}.
[I 2026-02-03 11:27:41,483] Trial 21 finished with values: [0.10711559090750467, 0.8928353635589703] and parameters: {'n_estimators': 110, 'max_depth': 71, 'min_samples_split': 13, 'min_samples_leaf': 19}.
[I 2026-02-03 11:27:42,271] Trial 28 finished with values: [0.055611111068378336, 0.944389545066468] and parameters: {'n_estimators': 13, 'max_depth': 43, 'min_samples_split': 2, 'min_samples_leaf': 3}.
[I 2026-02-03 11:27:42,570] Trial 25 finished with values: [0.06795912626118886, 0.9320344647339368] and parameters: {'n_estimators': 53, 'max_depth': 48, 'min_samples_split': 16, 'min_samples_leaf': 1}.
[I 2026-02-03 11:27:43,238] Trial 26 finished with values: [0.08750055454000515, 0.9124878191591032] and parameters: {'n_estimators': 109, 'max_depth': 22, 'min_samples_split': 12, 'min_samples_leaf': 12}.
[I 2026-02-03 11:27:43,269] Trial 23 finished with values: [0.09657926432151662, 0.9034060033606135] and parameters: {'n_estimators': 98, 'max_depth': 60, 'min_samples_split': 11, 'min_samples_leaf': 15}.
[I 2026-02-03 11:27:44,180] Trial 27 finished with values: [0.09346899218749391, 0.9065115621477766] and parameters: {'n_estimators': 100, 'max_depth': 83, 'min_samples_split': 11, 'min_samples_leaf': 14}.
[I 2026-02-03 11:27:44,902] Trial 32 finished with values: [0.06216684905286969, 0.9377850199511096] and parameters: {'n_estimators': 10, 'max_depth': 111, 'min_samples_split': 7, 'min_samples_leaf': 4}.
[I 2026-02-03 11:27:45,584] Trial 30 finished with values: [0.0916941902047593, 0.9082692501701377] and parameters: {'n_estimators': 98, 'max_depth': 34, 'min_samples_split': 15, 'min_samples_leaf': 13}.
[I 2026-02-03 11:27:45,790] Trial 31 finished with values: [0.09914964468392819, 0.9008275541244265] and parameters: {'n_estimators': 56, 'max_depth': 17, 'min_samples_split': 20, 'min_samples_leaf': 16}.
[I 2026-02-03 11:27:46,368] Trial 34 finished with values: [0.07833405644839406, 0.9216770466449855] and parameters: {'n_estimators': 29, 'max_depth': 93, 'min_samples_split': 4, 'min_samples_leaf': 9}.
[I 2026-02-03 11:27:46,484] Trial 29 finished with values: [0.09995534832322836, 0.9000225830249555] and parameters: {'n_estimators': 99, 'max_depth': 91, 'min_samples_split': 8, 'min_samples_leaf': 16}.
[I 2026-02-03 11:27:46,718] Trial 33 finished with values: [0.07805054664853117, 0.9219110057085527] and parameters: {'n_estimators': 51, 'max_depth': 120, 'min_samples_split': 14, 'min_samples_leaf': 9}.
[I 2026-02-03 11:27:48,007] Trial 36 finished with values: [0.07175668032973384, 0.9282367311053348] and parameters: {'n_estimators': 49, 'max_depth': 107, 'min_samples_split': 15, 'min_samples_leaf': 7}.
[I 2026-02-03 11:27:48,473] Trial 35 finished with values: [0.047126050696260025, 0.9528752572329827] and parameters: {'n_estimators': 53, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 2}.
[I 2026-02-03 11:27:48,959] Trial 37 finished with values: [0.08145811704071311, 0.9185375986195332] and parameters: {'n_estimators': 87, 'max_depth': 77, 'min_samples_split': 14, 'min_samples_leaf': 10}.
[I 2026-02-03 11:27:49,383] Trial 39 finished with values: [0.09996938415525328, 0.9000074786035774] and parameters: {'n_estimators': 41, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 16}.
[I 2026-02-03 11:27:50,808] Trial 38 finished with values: [0.1089058827461757, 0.8910449293799179] and parameters: {'n_estimators': 126, 'max_depth': 39, 'min_samples_split': 11, 'min_samples_leaf': 20}.
[I 2026-02-03 11:27:51,041] Trial 40 finished with values: [0.09064625882597646, 0.9093402035224158] and parameters: {'n_estimators': 70, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 13}.
[I 2026-02-03 11:27:52,322] Trial 42 finished with values: [0.08771459616935598, 0.9122696969084592] and parameters: {'n_estimators': 83, 'max_depth': 113, 'min_samples_split': 15, 'min_samples_leaf': 12}.
[I 2026-02-03 11:27:53,046] Trial 45 finished with values: [0.05929122119009651, 0.9407238922178829] and parameters: {'n_estimators': 12, 'max_depth': 112, 'min_samples_split': 8, 'min_samples_leaf': 3}.
[I 2026-02-03 11:27:53,429] Trial 41 finished with values: [0.05148254488371372, 0.9485062656064273] and parameters: {'n_estimators': 116, 'max_depth': 117, 'min_samples_split': 3, 'min_samples_leaf': 3}.
[I 2026-02-03 11:27:53,521] Trial 44 finished with values: [0.07750765509008761, 0.9224871834120624] and parameters: {'n_estimators': 84, 'max_depth': 48, 'min_samples_split': 12, 'min_samples_leaf': 9}.
[I 2026-02-03 11:27:53,981] Trial 46 finished with values: [0.10298147382660697, 0.8969562927687168] and parameters: {'n_estimators': 35, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 17}.
[I 2026-02-03 11:27:54,327] Trial 48 finished with values: [0.08959315804159214, 0.9103988198173198] and parameters: {'n_estimators': 21, 'max_depth': 76, 'min_samples_split': 20, 'min_samples_leaf': 12}.
[I 2026-02-03 11:27:55,267] Trial 43 finished with values: [0.06495738053242532, 0.935039513608468] and parameters: {'n_estimators': 143, 'max_depth': 67, 'min_samples_split': 7, 'min_samples_leaf': 6}.
[I 2026-02-03 11:27:56,949] Trial 47 finished with values: [0.07442758693198645, 0.9255741093992466] and parameters: {'n_estimators': 125, 'max_depth': 122, 'min_samples_split': 19, 'min_samples_leaf': 6}.
[I 2026-02-03 11:27:56,986] Trial 52 finished with values: [0.10855849264771418, 0.8914001588372809] and parameters: {'n_estimators': 10, 'max_depth': 150, 'min_samples_split': 4, 'min_samples_leaf': 17}.
[I 2026-02-03 11:27:57,124] Trial 51 finished with values: [0.05915543457266372, 0.940849880548954] and parameters: {'n_estimators': 17, 'max_depth': 63, 'min_samples_split': 6, 'min_samples_leaf': 4}.
[I 2026-02-03 11:27:58,758] Trial 50 finished with values: [0.09901175850852742, 0.900958715187825] and parameters: {'n_estimators': 127, 'max_depth': 135, 'min_samples_split': 13, 'min_samples_leaf': 16}.
[I 2026-02-03 11:27:59,273] Trial 49 finished with values: [0.056101195637487555, 0.9438996033681029] and parameters: {'n_estimators': 145, 'max_depth': 47, 'min_samples_split': 8, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:01,352] Trial 53 finished with values: [0.0734243965335985, 0.9265733837615407] and parameters: {'n_estimators': 124, 'max_depth': 146, 'min_samples_split': 13, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:01,493] Trial 56 finished with values: [0.09094444869956124, 0.9090176086972569] and parameters: {'n_estimators': 55, 'max_depth': 110, 'min_samples_split': 8, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:01,887] Trial 55 finished with values: [0.09410391640405036, 0.9058703701076052] and parameters: {'n_estimators': 94, 'max_depth': 121, 'min_samples_split': 12, 'min_samples_leaf': 14}.
[I 2026-02-03 11:28:02,122] Trial 58 finished with values: [0.07641669629396082, 0.9235691984142722] and parameters: {'n_estimators': 20, 'max_depth': 47, 'min_samples_split': 12, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:02,122] Trial 54 finished with values: [0.06239810092413066, 0.9375958799236821] and parameters: {'n_estimators': 147, 'max_depth': 94, 'min_samples_split': 13, 'min_samples_leaf': 1}.
[I 2026-02-03 11:28:02,989] Trial 57 finished with values: [0.08448715008329033, 0.9155205181482453] and parameters: {'n_estimators': 84, 'max_depth': 38, 'min_samples_split': 4, 'min_samples_leaf': 11}.
[I 2026-02-03 11:28:04,747] Trial 62 finished with values: [0.06171576609083061, 0.9382660861512395] and parameters: {'n_estimators': 11, 'max_depth': 48, 'min_samples_split': 4, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:06,126] Trial 60 finished with values: [0.07357078110345724, 0.9264192139359662] and parameters: {'n_estimators': 115, 'max_depth': 69, 'min_samples_split': 16, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:06,389] Trial 59 finished with values: [0.06493119074644332, 0.9350560247135562] and parameters: {'n_estimators': 103, 'max_depth': 106, 'min_samples_split': 14, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:07,618] Trial 61 finished with values: [0.09005141569194736, 0.9099336235787898] and parameters: {'n_estimators': 150, 'max_depth': 55, 'min_samples_split': 6, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:08,676] Trial 64 finished with values: [0.10160376309256232, 0.8983537771513277] and parameters: {'n_estimators': 86, 'max_depth': 21, 'min_samples_split': 18, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:09,507] Trial 63 finished with values: [0.04394914017278264, 0.9560415725884447] and parameters: {'n_estimators': 87, 'max_depth': 32, 'min_samples_split': 3, 'min_samples_leaf': 1}.
[I 2026-02-03 11:28:10,263] Trial 67 finished with values: [0.07796624311971312, 0.9220197024687835] and parameters: {'n_estimators': 54, 'max_depth': 109, 'min_samples_split': 15, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:10,554] Trial 65 finished with values: [0.08752232575472674, 0.9124692498918995] and parameters: {'n_estimators': 109, 'max_depth': 112, 'min_samples_split': 7, 'min_samples_leaf': 12}.
[I 2026-02-03 11:28:10,648] Trial 69 finished with values: [0.07429234232497636, 0.9257164106876239] and parameters: {'n_estimators': 22, 'max_depth': 72, 'min_samples_split': 18, 'min_samples_leaf': 6}.
[I 2026-02-03 11:28:11,059] Trial 66 finished with values: [0.08994790275035859, 0.9100255421509251] and parameters: {'n_estimators': 98, 'max_depth': 34, 'min_samples_split': 7, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:12,797] Trial 70 finished with values: [0.09108740250056721, 0.9089201316910518] and parameters: {'n_estimators': 70, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:13,098] Trial 68 finished with values: [0.0775892319410664, 0.9223899797265771] and parameters: {'n_estimators': 84, 'max_depth': 35, 'min_samples_split': 15, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:13,250] Trial 71 finished with values: [0.05191582037483211, 0.9480963985787101] and parameters: {'n_estimators': 78, 'max_depth': 43, 'min_samples_split': 2, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:14,447] Trial 75 finished with values: [0.09425154783966623, 0.9057630682376125] and parameters: {'n_estimators': 13, 'max_depth': 43, 'min_samples_split': 2, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:15,762] Trial 76 finished with values: [0.09103829228947932, 0.9089739888831397] and parameters: {'n_estimators': 31, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:15,807] Trial 72 finished with values: [0.0650129029036363, 0.934975466221994] and parameters: {'n_estimators': 83, 'max_depth': 94, 'min_samples_split': 15, 'min_samples_leaf': 10}.
[I 2026-02-03 11:28:16,331] Trial 74 finished with values: [0.09038131834165292, 0.9095892774375333] and parameters: {'n_estimators': 109, 'max_depth': 70, 'min_samples_split': 12, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:16,871] Trial 77 finished with values: [0.06151168870555736, 0.938465425871272] and parameters: {'n_estimators': 50, 'max_depth': 59, 'min_samples_split': 9, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:17,913] Trial 73 finished with values: [0.06078755364063898, 0.9392194452722634] and parameters: {'n_estimators': 122, 'max_depth': 94, 'min_samples_split': 12, 'min_samples_leaf': 1}.
[I 2026-02-03 11:28:18,029] Trial 80 finished with values: [0.10410801300359593, 0.8958511296485044] and parameters: {'n_estimators': 53, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 18}.
[I 2026-02-03 11:28:18,203] Trial 78 finished with values: [0.061400530229856885, 0.9385819189514917] and parameters: {'n_estimators': 70, 'max_depth': 23, 'min_samples_split': 4, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:18,233] Trial 79 finished with values: [0.053612534736121986, 0.9463682615758777] and parameters: {'n_estimators': 32, 'max_depth': 70, 'min_samples_split': 2, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:18,527] Trial 83 finished with values: [0.07859345598073067, 0.9213644521731734] and parameters: {'n_estimators': 10, 'max_depth': 111, 'min_samples_split': 19, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:21,363] Trial 84 finished with values: [0.10129558106909542, 0.8986505082925674] and parameters: {'n_estimators': 123, 'max_depth': 100, 'min_samples_split': 9, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:21,473] Trial 81 finished with values: [0.07743784552221575, 0.9225568852398407] and parameters: {'n_estimators': 118, 'max_depth': 113, 'min_samples_split': 8, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:21,706] Trial 82 finished with values: [0.08744307242629756, 0.912543640366694] and parameters: {'n_estimators': 109, 'max_depth': 43, 'min_samples_split': 12, 'min_samples_leaf': 12}.
[I 2026-02-03 11:28:23,126] Trial 85 finished with values: [0.08123954357932665, 0.9187633925499824] and parameters: {'n_estimators': 87, 'max_depth': 77, 'min_samples_split': 14, 'min_samples_leaf': 10}.
[I 2026-02-03 11:28:23,243] Trial 87 finished with values: [0.07173227690935914, 0.9282496272394273] and parameters: {'n_estimators': 49, 'max_depth': 48, 'min_samples_split': 16, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:23,515] Trial 89 finished with values: [0.0740730657465212, 0.9259301992536197] and parameters: {'n_estimators': 16, 'max_depth': 115, 'min_samples_split': 17, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:24,755] Trial 86 finished with values: [0.06655743016393204, 0.9334295364887181] and parameters: {'n_estimators': 143, 'max_depth': 43, 'min_samples_split': 15, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:24,756] Trial 91 finished with values: [0.11192613568303966, 0.8880236341365946] and parameters: {'n_estimators': 16, 'max_depth': 100, 'min_samples_split': 9, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:25,206] Trial 88 finished with values: [0.09668332355872171, 0.9032852138420397] and parameters: {'n_estimators': 98, 'max_depth': 111, 'min_samples_split': 11, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:25,805] Trial 92 finished with values: [0.0779842415830164, 0.9220097434717879] and parameters: {'n_estimators': 53, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:26,654] Trial 94 finished with values: [0.08161961291359043, 0.9183611647543384] and parameters: {'n_estimators': 32, 'max_depth': 70, 'min_samples_split': 14, 'min_samples_leaf': 10}.
[I 2026-02-03 11:28:27,969] Trial 93 finished with values: [0.07776628630642794, 0.9222261498371875] and parameters: {'n_estimators': 99, 'max_depth': 113, 'min_samples_split': 9, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:29,613] Trial 96 finished with values: [0.0692781207205116, 0.9307352529212558] and parameters: {'n_estimators': 74, 'max_depth': 106, 'min_samples_split': 17, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:30,899] Trial 95 finished with values: [0.06020479587856649, 0.9397669236145232] and parameters: {'n_estimators': 125, 'max_depth': 143, 'min_samples_split': 11, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:31,141] Trial 98 finished with values: [0.056593169457362466, 0.9433967287007746] and parameters: {'n_estimators': 53, 'max_depth': 111, 'min_samples_split': 7, 'min_samples_leaf': 4}.

c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:416: ExperimentalWarning: optuna.visualization.matplotlib._pareto_front.plot_pareto_front is experimental (supported from v2.8.0). The interface can change in the future.
  ax = vis.plot_pareto_front(study, target_names=target_names)
c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:425: ExperimentalWarning: optuna.visualization.matplotlib._optimization_history.plot_optimization_history is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_optimization_history(
c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:436: ExperimentalWarning: optuna.visualization.matplotlib._optimization_history.plot_optimization_history is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_optimization_history(
c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:447: ExperimentalWarning: optuna.visualization.matplotlib._param_importances.plot_param_importances is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_param_importances(study)

  Optuna plots for RFR saved in 'ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\plots' directory.
  Best model saved to: ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\models\RFR_best_model.pkl
  Y-Y plot saved to: ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\plots\RFR_yy_plot.png

--- Workflow Complete ---
✓ Results summary saved to: ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\results.csv
✓ Detailed results saved to: ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\results_detailed.txt
✓ Models saved to: ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\models
✓ Plots saved to: ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\plots
✓ Studies saved to: ground_truth_models/FeCoNiCrV_Min_CTE_Max_K\studies
    Model  Optimization Time (s)  Retraining Time (s)  \
0  Linear                  0.000                0.002
1     RFR                 80.322                2.049

                                         Best Params Train R2 (Per-Output)  \
0                                                 {}       [0.5423, 0.513]
1  {'n_estimators': 87, 'max_depth': 32, 'min_sam...      [0.9867, 0.9981]

  Train MSE (Per-Output) Train MAE (Per-Output) Test R2 (Per-Output)  \
0  [2.405218, 58.956718]   [0.929491, 5.426511]       [0.556, 0.493]
1   [0.069933, 0.231919]   [0.101774, 0.239303]     [0.9311, 0.9919]

   Test MSE (Per-Output) Test MAE (Per-Output)
0  [2.249023, 59.235418]  [0.909255, 5.448413]
1   [0.348915, 0.946258]  [0.216597, 0.482786]

In [8]:
# Path to your Excel training data
TRAINING_XLSX = "data/1000_refractory_alloy_calphad_modeled_data.xlsx"

# Input columns must match the component labels / order used in DesignSpace
INPUT_COLS = ["Ti", "V", "Nb", "Mo", "Hf", "Ta", "W"]

# Target columns in your Excel sheet
TARGET_COLS = [
    "PROP RT Therm Cond (W/(mK))",
    "Sconf",
]

# Where to save the optimized models, scalers, plots, and optimization studies and results
OUTPUT_DIR = "ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond"
os.makedirs(OUTPUT_DIR, exist_ok=True)

MODELS_PATH = os.path.join(OUTPUT_DIR, "models")
PLOTS_PATH = os.path.join(OUTPUT_DIR, "plots")
STUDIES_PATH = os.path.join(OUTPUT_DIR, "studies")
RESULTS_PATH = OUTPUT_DIR

In [9]:
# If your data is on a specific sheet, pass sheet_name="Sheet1" (or the right name).
df = pd.read_excel(TRAINING_XLSX)  # , sheet_name="Sheet1"
df.head()

,Unnamed: 0,Ti,V,Nb,Mo,Hf,Ta,W,System Type,Unnamed: 0.2,...,Atomic Planar Density_Var,C_11_Avg,C_11_Var,C_12_Avg,C_12_Var,C'_Avg,C'_Var,Bulk Modulus (GPa)_Avg,Bulk Modulus (GPa)_Var,Pugh Ratio
0,500,0.05,0.000,0.575,0.100,0.0,0.225,0.050,17,77984,...,5.178468,16.650,39.770938,36.150,94.433191,-9.7500,31.358611,186.75,37.972852,3.132075
1,682,0.10,0.000,0.475,0.100,0.0,0.325,0.000,58,96328,...,5.697076,22.800,45.777287,41.100,95.001526,-9.1500,31.652843,179.75,30.289231,3.160440
2,809,0.05,0.000,0.600,0.050,0.0,0.225,0.075,17,80189,...,4.271883,11.400,34.318217,20.550,70.249181,-4.5750,22.844734,187.25,41.652581,3.195392
3,139,0.00,0.050,0.600,0.075,0.0,0.200,0.075,16,76428,...,5.118709,8.875,27.714786,36.350,96.610183,-13.7375,36.451507,190.50,38.791107,3.173678
4,766,0.05,0.025,0.550,0.125,0.0,0.250,0.000,28,93443,...,5.914301,19.775,41.875104,50.425,108.592792,-15.3250,38.319471,181.75,26.822332,3.215391

In [10]:
# Extract inputs (X) and targets (y)
X_raw = df[INPUT_COLS]
y_raw = df[TARGET_COLS]

print("X_raw shape:", X_raw.shape)
print("y_raw shape:", y_raw.shape)

X_raw shape: (1000, 7)
y_raw shape: (1000, 2)

In [11]:
# Define models
models = {
    "Linear": LinearRegression(),
    "RFR": RandomForestRegressor()
}

In [12]:
# Define hyperparameter spaces for optimization
param_spaces = {
    "RFR": {
        "n_estimators": ('int', 10, 150),   # Number of trees
        "max_depth": ('int', 10, 150),         # Maximum depth of trees
        "min_samples_split": ('int', 2, 20), # Minimum number of samples required to split an internal node
        "min_samples_leaf": ('int', 1, 20)   # Minimum number of samples required to be at a leaf node
    }
}

In [13]:
# Import the run_workflow function from workflow.py
from core.armote_multi_output import run_workflow

# Define output labels
output_labels = ['K (W/(m·K))', 'ΔSᶜᵒⁿᶠⁱᵍ (R)']

# Define the folder dictionary
folder_dict = {
    'models': MODELS_PATH,
    'plots': PLOTS_PATH,
    'studies': STUDIES_PATH,
    'results': RESULTS_PATH
    }

# Run the workflow
results_df = run_workflow(X_raw, y_raw, models, param_spaces, output_labels=output_labels, folder_dict=folder_dict)

# Display the results DataFrame
print(results_df)

Setting up output folders...
✓ Models folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\TiVNbMoHfTaW_Max_S_Max_TCond\models
✓ Plots folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\TiVNbMoHfTaW_Max_S_Max_TCond\plots
✓ Studies folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\TiVNbMoHfTaW_Max_S_Max_TCond\studies
✓ Results folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\TiVNbMoHfTaW_Max_S_Max_TCond

Initializing multi-output workflow...
NOTE: Optimization uses SCALED data for fair comparison across outputs
      Reporting includes normalized metrics (RMSE/std) for fair comparison

Fitting and saving data scalers...
  Scalers saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\models

--- Starting Workflow for: Linear ---
  Checking multi-output support for LinearRegression...
  → LinearRegression supports multi-output natively.
  No hyperparameters defined. Training model with default settings.
  Retraining the final model with the best hyperparameters...
  Final model training complete in 0.001 seconds.
  Best model saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\models\Linear_best_model.pkl

[I 2026-02-03 11:28:43,689] A new study created in memory with name: no-name-e71b6dff-bac5-4bfc-98b2-a4a24d7e7638

  Y-Y plot saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\plots\Linear_yy_plot.png

--- Starting Workflow for: RFR ---
  Checking multi-output support for RandomForestRegressor...
  → RandomForestRegressor supports multi-output natively.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-02-03 11:28:44,400] Trial 0 finished with values: [0.16521056366215547, 0.8337993376652723] and parameters: {'n_estimators': 101, 'max_depth': 105, 'min_samples_split': 15, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:44,429] Trial 1 finished with values: [0.1660273508086155, 0.8336180486232445] and parameters: {'n_estimators': 147, 'max_depth': 63, 'min_samples_split': 18, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:45,462] Trial 7 finished with values: [0.11714934974549147, 0.8819880855948823] and parameters: {'n_estimators': 30, 'max_depth': 126, 'min_samples_split': 9, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:45,478] Trial 2 finished with values: [0.1651942842243716, 0.8333636254599363] and parameters: {'n_estimators': 10, 'max_depth': 95, 'min_samples_split': 19, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:46,259] Trial 11 finished with values: [0.1180223685380694, 0.881168609567459] and parameters: {'n_estimators': 145, 'max_depth': 111, 'min_samples_split': 20, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:46,353] Trial 3 finished with values: [0.12926730124006267, 0.8693087998533866] and parameters: {'n_estimators': 106, 'max_depth': 145, 'min_samples_split': 15, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:46,480] Trial 10 finished with values: [0.11848765449049985, 0.8806345435761852] and parameters: {'n_estimators': 41, 'max_depth': 32, 'min_samples_split': 20, 'min_samples_leaf': 11}.
[I 2026-02-03 11:28:46,545] Trial 9 finished with values: [0.11766372476507872, 0.8815500912070275] and parameters: {'n_estimators': 143, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:46,669] Trial 8 finished with values: [0.11701499057489115, 0.8822014907925636] and parameters: {'n_estimators': 147, 'max_depth': 40, 'min_samples_split': 20, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:46,762] Trial 13 finished with values: [0.11697252642527071, 0.8822552871035769] and parameters: {'n_estimators': 89, 'max_depth': 100, 'min_samples_split': 6, 'min_samples_leaf': 12}.
[I 2026-02-03 11:28:46,826] Trial 5 finished with values: [0.11831568498527154, 0.8808756322358822] and parameters: {'n_estimators': 95, 'max_depth': 19, 'min_samples_split': 11, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:47,170] Trial 4 finished with values: [0.11783944863456845, 0.8812996563568299] and parameters: {'n_estimators': 86, 'max_depth': 130, 'min_samples_split': 9, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:47,603] Trial 17 finished with values: [0.20121982680164402, 0.7974459293792714] and parameters: {'n_estimators': 13, 'max_depth': 56, 'min_samples_split': 5, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:47,695] Trial 14 finished with values: [0.1164801773788107, 0.8827249637533816] and parameters: {'n_estimators': 122, 'max_depth': 147, 'min_samples_split': 3, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:47,793] Trial 15 finished with values: [0.11901570564773623, 0.8801058507432786] and parameters: {'n_estimators': 145, 'max_depth': 107, 'min_samples_split': 10, 'min_samples_leaf': 1}.
[I 2026-02-03 11:28:47,853] Trial 6 finished with values: [0.11928430215206302, 0.8798977180101195] and parameters: {'n_estimators': 42, 'max_depth': 100, 'min_samples_split': 19, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:47,947] Trial 12 finished with values: [0.1194328307577813, 0.8797341301540971] and parameters: {'n_estimators': 149, 'max_depth': 17, 'min_samples_split': 17, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:48,153] Trial 18 finished with values: [0.1366600890626667, 0.8623826822799934] and parameters: {'n_estimators': 126, 'max_depth': 121, 'min_samples_split': 3, 'min_samples_leaf': 6}.
[I 2026-02-03 11:28:48,166] Trial 19 finished with values: [0.14060679706844104, 0.8582404790003728] and parameters: {'n_estimators': 33, 'max_depth': 58, 'min_samples_split': 17, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:48,273] Trial 20 finished with values: [0.10932688331821774, 0.8899524353245608] and parameters: {'n_estimators': 83, 'max_depth': 51, 'min_samples_split': 7, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:48,662] Trial 23 finished with values: [0.1648380404286007, 0.8340686963794826] and parameters: {'n_estimators': 78, 'max_depth': 122, 'min_samples_split': 5, 'min_samples_leaf': 10}.
[I 2026-02-03 11:28:48,898] Trial 16 finished with values: [0.12546511665834065, 0.8736197266861655] and parameters: {'n_estimators': 139, 'max_depth': 150, 'min_samples_split': 6, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:48,960] Trial 26 finished with values: [0.1345896846490465, 0.8642943726262334] and parameters: {'n_estimators': 38, 'max_depth': 80, 'min_samples_split': 12, 'min_samples_leaf': 6}.
[I 2026-02-03 11:28:48,993] Trial 21 finished with values: [0.10140121803232845, 0.897977177658424] and parameters: {'n_estimators': 139, 'max_depth': 31, 'min_samples_split': 4, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:49,038] Trial 24 finished with values: [0.1738074950701986, 0.8249914656124535] and parameters: {'n_estimators': 111, 'max_depth': 41, 'min_samples_split': 12, 'min_samples_leaf': 11}.
[I 2026-02-03 11:28:49,054] Trial 25 finished with values: [0.20851848418891583, 0.7906221515228402] and parameters: {'n_estimators': 32, 'max_depth': 115, 'min_samples_split': 12, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:49,100] Trial 28 finished with values: [0.19748952604833483, 0.8013591900276591] and parameters: {'n_estimators': 17, 'max_depth': 78, 'min_samples_split': 17, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:49,117] Trial 30 finished with values: [0.16212194598668245, 0.8367884380568146] and parameters: {'n_estimators': 13, 'max_depth': 83, 'min_samples_split': 12, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:49,396] Trial 22 finished with values: [0.11784764352243364, 0.8813030315175322] and parameters: {'n_estimators': 90, 'max_depth': 102, 'min_samples_split': 10, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:49,447] Trial 27 finished with values: [0.2151178399548357, 0.7841717873277063] and parameters: {'n_estimators': 51, 'max_depth': 54, 'min_samples_split': 4, 'min_samples_leaf': 20}.
[I 2026-02-03 11:28:49,647] Trial 31 finished with values: [0.1580126340553305, 0.8408784930420523] and parameters: {'n_estimators': 79, 'max_depth': 51, 'min_samples_split': 2, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:49,759] Trial 35 finished with values: [0.1439672801472181, 0.8549741742859156] and parameters: {'n_estimators': 43, 'max_depth': 63, 'min_samples_split': 5, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:49,940] Trial 32 finished with values: [0.1589319528094217, 0.8398760375519266] and parameters: {'n_estimators': 48, 'max_depth': 107, 'min_samples_split': 11, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:49,967] Trial 34 finished with values: [0.20768167040731084, 0.7913169786726402] and parameters: {'n_estimators': 34, 'max_depth': 145, 'min_samples_split': 2, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:50,023] Trial 29 finished with values: [0.19301667937199038, 0.8056961598922745] and parameters: {'n_estimators': 117, 'max_depth': 85, 'min_samples_split': 12, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:50,038] Trial 36 finished with values: [0.1806561635733857, 0.8181836613505762] and parameters: {'n_estimators': 84, 'max_depth': 13, 'min_samples_split': 19, 'min_samples_leaf': 12}.
[I 2026-02-03 11:28:50,100] Trial 39 finished with values: [0.127810220007651, 0.8714225048308432] and parameters: {'n_estimators': 10, 'max_depth': 147, 'min_samples_split': 10, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:50,151] Trial 38 finished with values: [0.20480762142964135, 0.7940100682697576] and parameters: {'n_estimators': 66, 'max_depth': 42, 'min_samples_split': 12, 'min_samples_leaf': 18}.
[I 2026-02-03 11:28:50,194] Trial 40 finished with values: [0.14438315986278003, 0.8545735386194545] and parameters: {'n_estimators': 129, 'max_depth': 30, 'min_samples_split': 20, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:50,256] Trial 33 finished with values: [0.14691108282589602, 0.8520896004894178] and parameters: {'n_estimators': 76, 'max_depth': 138, 'min_samples_split': 19, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:50,398] Trial 41 finished with values: [0.13733880333767376, 0.8617451221096741] and parameters: {'n_estimators': 30, 'max_depth': 99, 'min_samples_split': 18, 'min_samples_leaf': 1}.
[I 2026-02-03 11:28:50,414] Trial 37 finished with values: [0.14498815381978583, 0.8540068886778819] and parameters: {'n_estimators': 69, 'max_depth': 123, 'min_samples_split': 5, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:50,664] Trial 43 finished with values: [0.1335183182243874, 0.8654738378650115] and parameters: {'n_estimators': 53, 'max_depth': 33, 'min_samples_split': 14, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:50,741] Trial 46 finished with values: [0.1889288276806993, 0.8099431099051475] and parameters: {'n_estimators': 26, 'max_depth': 54, 'min_samples_split': 20, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:50,804] Trial 44 finished with values: [0.1500904246824611, 0.8488250284912346] and parameters: {'n_estimators': 84, 'max_depth': 10, 'min_samples_split': 18, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:50,819] Trial 45 finished with values: [0.15985688808934675, 0.8390513719150754] and parameters: {'n_estimators': 25, 'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:50,928] Trial 42 finished with values: [0.21221325099837074, 0.7869096288680019] and parameters: {'n_estimators': 116, 'max_depth': 109, 'min_samples_split': 11, 'min_samples_leaf': 20}.
[I 2026-02-03 11:28:50,990] Trial 47 finished with values: [0.18638861503487994, 0.8123117192924194] and parameters: {'n_estimators': 35, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:51,117] Trial 50 finished with values: [0.1527627471520188, 0.8460879588409884] and parameters: {'n_estimators': 31, 'max_depth': 18, 'min_samples_split': 20, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:51,134] Trial 48 finished with values: [0.21280584974239142, 0.7863061710226049] and parameters: {'n_estimators': 51, 'max_depth': 55, 'min_samples_split': 2, 'min_samples_leaf': 20}.
[I 2026-02-03 11:28:51,164] Trial 52 finished with values: [0.19612652936889155, 0.8026208783296358] and parameters: {'n_estimators': 23, 'max_depth': 90, 'min_samples_split': 9, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:51,195] Trial 53 finished with values: [0.19217259911254095, 0.8064837568839263] and parameters: {'n_estimators': 28, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 14}.
[I 2026-02-03 11:28:51,259] Trial 49 finished with values: [0.17983145358981245, 0.8190383692643511] and parameters: {'n_estimators': 69, 'max_depth': 79, 'min_samples_split': 16, 'min_samples_leaf': 12}.
[I 2026-02-03 11:28:51,539] Trial 56 finished with values: [0.13094840157964088, 0.8679541374990457] and parameters: {'n_estimators': 38, 'max_depth': 136, 'min_samples_split': 12, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:51,572] Trial 54 finished with values: [0.1477249297759562, 0.8510747297116931] and parameters: {'n_estimators': 48, 'max_depth': 56, 'min_samples_split': 15, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:51,635] Trial 55 finished with values: [0.11781392319446012, 0.8813084293053084] and parameters: {'n_estimators': 57, 'max_depth': 40, 'min_samples_split': 9, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:51,863] Trial 51 finished with values: [0.21353192249048308, 0.7856988346191309] and parameters: {'n_estimators': 114, 'max_depth': 59, 'min_samples_split': 19, 'min_samples_leaf': 20}.
[I 2026-02-03 11:28:51,982] Trial 57 finished with values: [0.17823255125876997, 0.8205619935702352] and parameters: {'n_estimators': 137, 'max_depth': 116, 'min_samples_split': 2, 'min_samples_leaf': 12}.
[I 2026-02-03 11:28:52,185] Trial 61 finished with values: [0.15658364998443608, 0.842181754508354] and parameters: {'n_estimators': 37, 'max_depth': 45, 'min_samples_split': 15, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:52,215] Trial 58 finished with values: [0.2022454943742468, 0.7965820034279087] and parameters: {'n_estimators': 130, 'max_depth': 34, 'min_samples_split': 17, 'min_samples_leaf': 18}.
[I 2026-02-03 11:28:52,263] Trial 59 finished with values: [0.10380368033529322, 0.8954599086844958] and parameters: {'n_estimators': 66, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:52,355] Trial 60 finished with values: [0.14091270553478133, 0.8580959297088164] and parameters: {'n_estimators': 57, 'max_depth': 53, 'min_samples_split': 16, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:52,525] Trial 62 finished with values: [0.20392943507646333, 0.794875729971401] and parameters: {'n_estimators': 108, 'max_depth': 41, 'min_samples_split': 13, 'min_samples_leaf': 18}.
[I 2026-02-03 11:28:52,686] Trial 63 finished with values: [0.19732361449288408, 0.8016077430669395] and parameters: {'n_estimators': 113, 'max_depth': 104, 'min_samples_split': 3, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:52,905] Trial 65 finished with values: [0.1483973083584819, 0.8507215669731252] and parameters: {'n_estimators': 143, 'max_depth': 32, 'min_samples_split': 20, 'min_samples_leaf': 11}.
[I 2026-02-03 11:28:52,992] Trial 66 finished with values: [0.10823676339682595, 0.8910435114632035] and parameters: {'n_estimators': 90, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:53,140] Trial 64 finished with values: [0.12721424422765096, 0.8711587879087105] and parameters: {'n_estimators': 42, 'max_depth': 100, 'min_samples_split': 19, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:53,282] Trial 70 finished with values: [0.18612300615377425, 0.8126936764070745] and parameters: {'n_estimators': 26, 'max_depth': 102, 'min_samples_split': 10, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:53,339] Trial 67 finished with values: [0.19459246905882632, 0.8040960386681565] and parameters: {'n_estimators': 106, 'max_depth': 99, 'min_samples_split': 15, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:53,455] Trial 69 finished with values: [0.158207450515118, 0.8406349641464559] and parameters: {'n_estimators': 79, 'max_depth': 51, 'min_samples_split': 12, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:53,630] Trial 68 finished with values: [0.20118904912741464, 0.7975717794030244] and parameters: {'n_estimators': 143, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:53,764] Trial 74 finished with values: [0.15946135245054563, 0.8395111184202397] and parameters: {'n_estimators': 30, 'max_depth': 97, 'min_samples_split': 17, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:53,827] Trial 71 finished with values: [0.19358067178352617, 0.8052242634577604] and parameters: {'n_estimators': 106, 'max_depth': 24, 'min_samples_split': 15, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:54,063] Trial 76 finished with values: [0.19675396456231248, 0.8019288375775439] and parameters: {'n_estimators': 31, 'max_depth': 111, 'min_samples_split': 14, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:54,156] Trial 75 finished with values: [0.1524437138037969, 0.8464242671162326] and parameters: {'n_estimators': 83, 'max_depth': 126, 'min_samples_split': 7, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:54,299] Trial 72 finished with values: [0.151635714691931, 0.8472050747827226] and parameters: {'n_estimators': 147, 'max_depth': 146, 'min_samples_split': 20, 'min_samples_leaf': 6}.
[I 2026-02-03 11:28:54,315] Trial 73 finished with values: [0.12430968805105036, 0.8748000482246105] and parameters: {'n_estimators': 147, 'max_depth': 147, 'min_samples_split': 11, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:54,831] Trial 78 finished with values: [0.2000707922069825, 0.798783077695383] and parameters: {'n_estimators': 143, 'max_depth': 95, 'min_samples_split': 19, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:54,861] Trial 81 finished with values: [0.1362677802374718, 0.8626747531522915] and parameters: {'n_estimators': 38, 'max_depth': 40, 'min_samples_split': 12, 'min_samples_leaf': 6}.
[I 2026-02-03 11:28:54,876] Trial 79 finished with values: [0.19636277805131105, 0.8025334080494065] and parameters: {'n_estimators': 89, 'max_depth': 36, 'min_samples_split': 18, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:54,955] Trial 77 finished with values: [0.1516999737193613, 0.8471836629655174] and parameters: {'n_estimators': 139, 'max_depth': 31, 'min_samples_split': 12, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:55,328] Trial 82 finished with values: [0.14292600736772343, 0.8559257949137159] and parameters: {'n_estimators': 106, 'max_depth': 146, 'min_samples_split': 12, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:55,391] Trial 83 finished with values: [0.14363029002369548, 0.8554392862048225] and parameters: {'n_estimators': 69, 'max_depth': 123, 'min_samples_split': 5, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:55,393] Trial 84 finished with values: [0.20805714398596198, 0.7908931541322939] and parameters: {'n_estimators': 63, 'max_depth': 147, 'min_samples_split': 15, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:55,438] Trial 80 finished with values: [0.12596694231652586, 0.8732012360732799] and parameters: {'n_estimators': 139, 'max_depth': 62, 'min_samples_split': 6, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:55,484] Trial 85 finished with values: [0.19511014839812918, 0.8035890559303633] and parameters: {'n_estimators': 69, 'max_depth': 147, 'min_samples_split': 5, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:55,729] Trial 86 finished with values: [0.10016521771410716, 0.8992063859951255] and parameters: {'n_estimators': 84, 'max_depth': 31, 'min_samples_split': 4, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:55,858] Trial 88 finished with values: [0.13220191831814265, 0.8668345035600591] and parameters: {'n_estimators': 53, 'max_depth': 33, 'min_samples_split': 14, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:55,903] Trial 89 finished with values: [0.15985249989090805, 0.8390154475300552] and parameters: {'n_estimators': 48, 'max_depth': 47, 'min_samples_split': 11, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:56,236] Trial 90 finished with values: [0.14536571198408962, 0.8535327286873127] and parameters: {'n_estimators': 71, 'max_depth': 147, 'min_samples_split': 19, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:56,397] Trial 93 finished with values: [0.15266121369472407, 0.8462852298708141] and parameters: {'n_estimators': 38, 'max_depth': 80, 'min_samples_split': 20, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:56,532] Trial 87 finished with values: [0.14258823524761272, 0.8563944349798804] and parameters: {'n_estimators': 138, 'max_depth': 130, 'min_samples_split': 5, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:56,677] Trial 92 finished with values: [0.1958013328530233, 0.8029957075582633] and parameters: {'n_estimators': 145, 'max_depth': 33, 'min_samples_split': 14, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:57,102] Trial 97 finished with values: [0.1443421468921258, 0.854629100205098] and parameters: {'n_estimators': 74, 'max_depth': 126, 'min_samples_split': 18, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:57,258] Trial 91 finished with values: [0.1511887425085771, 0.8476895692237638] and parameters: {'n_estimators': 143, 'max_depth': 147, 'min_samples_split': 3, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:57,310] Trial 95 finished with values: [0.20863387296644662, 0.790282898220329] and parameters: {'n_estimators': 89, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:57,338] Trial 94 finished with values: [0.1503286226400144, 0.8486208258539168] and parameters: {'n_estimators': 117, 'max_depth': 53, 'min_samples_split': 16, 'min_samples_leaf': 8}.

c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:416: ExperimentalWarning: optuna.visualization.matplotlib._pareto_front.plot_pareto_front is experimental (supported from v2.8.0). The interface can change in the future.
  ax = vis.plot_pareto_front(study, target_names=target_names)
c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:425: ExperimentalWarning: optuna.visualization.matplotlib._optimization_history.plot_optimization_history is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_optimization_history(
c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:436: ExperimentalWarning: optuna.visualization.matplotlib._optimization_history.plot_optimization_history is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_optimization_history(
c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:447: ExperimentalWarning: optuna.visualization.matplotlib._param_importances.plot_param_importances is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_param_importances(study)

  Optuna plots for RFR saved in 'ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\plots' directory.
  Best model saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\models\RFR_best_model.pkl
  Y-Y plot saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\plots\RFR_yy_plot.png

--- Workflow Complete ---
✓ Results summary saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\results.csv
✓ Detailed results saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\results_detailed.txt
✓ Models saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\models
✓ Plots saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\plots
✓ Studies saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\studies
    Model  Optimization Time (s)  Retraining Time (s)  \
0  Linear                  0.000                0.001
1     RFR                 13.896                0.275

                                         Best Params Train R2 (Per-Output)  \
0                                                 {}      [0.7096, 0.5319]
1  {'n_estimators': 84, 'max_depth': 31, 'min_sam...      [0.9919, 0.9552]

  Train MSE (Per-Output) Train MAE (Per-Output) Test R2 (Per-Output)  \
0   [10.00024, 0.005514]    [2.23758, 0.059447]     [0.6969, 0.5537]
1   [0.278666, 0.000527]     [0.4066, 0.018603]     [0.9836, 0.8496]

   Test MSE (Per-Output) Test MAE (Per-Output)
0  [13.698718, 0.005524]    [2.594429, 0.0618]
1   [0.742405, 0.001862]  [0.648493, 0.034869]