In [24]:
import os
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

# Path to your Excel training data
TRAINING_XLSX = "data/refractory-meltingvsdensity.xlsx"

# Input columns must match the component labels / order used in DesignSpace
INPUT_COLS = ["Ti", "V", "Nb", "Mo", "Hf", "Ta", "W"]

# Target columns in your Excel sheet
TARGET_COLS = [
    "Melting Point (K)",
    "PROP RT Density (g/cm3)",
]

# Where to save the optimized models, scalers, plots, and optimization studies and results
OUTPUT_DIR = "ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity"
os.makedirs(OUTPUT_DIR, exist_ok=True)

MODELS_PATH = os.path.join(OUTPUT_DIR, "models")
PLOTS_PATH = os.path.join(OUTPUT_DIR, "plots")
STUDIES_PATH = os.path.join(OUTPUT_DIR, "studies")
RESULTS_PATH = OUTPUT_DIR

In [25]:
# If your data is on a specific sheet, pass sheet_name="Sheet1" (or the right name).
df = pd.read_excel(TRAINING_XLSX)  # , sheet_name="Sheet1"
df.head()

,Unnamed: 0,Ti,V,Nb,Mo,Hf,Ta,W,PROP RT Density (g/cm3),Melting Point (K),Melting Point (°C)_Avg
0,500,0.05,0.000,0.575,0.100,0.0,0.225,0.050,10.936837,2893.050,2619.900
1,682,0.10,0.000,0.475,0.100,0.0,0.325,0.000,11.031867,2859.350,2586.200
2,809,0.05,0.000,0.600,0.050,0.0,0.225,0.075,11.100408,2909.375,2636.225
3,139,0.00,0.050,0.600,0.075,0.0,0.200,0.075,11.065715,2911.625,2638.475
4,766,0.05,0.025,0.550,0.125,0.0,0.250,0.000,10.702152,2848.775,2575.625

In [3]:
# Convert CTE
df['CTE (x 10^(-6) 1/K)'] = df['CTE (1/K)'] * 1e6
df.head()

,Fe,Co,Ni,Cr,V,CTE (1/K),K (W/(mK)),K/CTE,CTE (x 10^(-6) 1/K)
0,0.1,0.1,0.1,0.30,0.40,0.000009,7.447543,819403.1824,9.09
1,0.1,0.1,0.1,0.32,0.38,0.000009,7.715431,852620.8795,9.05
2,0.1,0.1,0.1,0.34,0.36,0.000009,7.956606,882843.4959,9.01
3,0.1,0.1,0.1,0.36,0.34,0.000009,8.171040,910002.9011,8.98
4,0.1,0.1,0.1,0.38,0.32,0.000009,8.359425,934130.3152,8.95

In [26]:
# Extract inputs (X) and targets (y)
X_raw = df[INPUT_COLS]
y_raw = df[TARGET_COLS]

print("X_raw shape:", X_raw.shape)
print("y_raw shape:", y_raw.shape)

X_raw shape: (1000, 7)
y_raw shape: (1000, 2)

In [27]:
# Define models
models = {
    "Linear": LinearRegression(),
    "RFR": RandomForestRegressor()
}

In [28]:
# Define hyperparameter spaces for optimization
param_spaces = {
    "RFR": {
        "n_estimators": ('int', 10, 150),   # Number of trees
        "max_depth": ('int', 10, 150),         # Maximum depth of trees
        "min_samples_split": ('int', 2, 20), # Minimum number of samples required to split an internal node
        "min_samples_leaf": ('int', 1, 20)   # Minimum number of samples required to be at a leaf node
    }
}

In [31]:
# Import the run_workflow function from workflow.py
from core.armote_multi_output import run_workflow

# Define output labels
output_labels = ['Melting Point (K)', 'Density (g/cm3)']

# Define the folder dictionary
folder_dict = {
    'models': MODELS_PATH,
    'plots': PLOTS_PATH,
    'studies': STUDIES_PATH,
    'results': RESULTS_PATH
    }

# Run the workflow
results_df = run_workflow(X_raw, y_raw, models, param_spaces, output_labels=output_labels, folder_dict=folder_dict)

# Display the results DataFrame
print(results_df)

Setting up output folders...
✓ Models folder ready: c:\Users\trippr5118\Documents\Research\resource-allocation\ground_truth_models\TiVNbMoHfTaW-MeltingVsDensity\models
✓ Plots folder ready: c:\Users\trippr5118\Documents\Research\resource-allocation\ground_truth_models\TiVNbMoHfTaW-MeltingVsDensity\plots
✓ Studies folder ready: c:\Users\trippr5118\Documents\Research\resource-allocation\ground_truth_models\TiVNbMoHfTaW-MeltingVsDensity\studies
✓ Results folder ready: c:\Users\trippr5118\Documents\Research\resource-allocation\ground_truth_models\TiVNbMoHfTaW-MeltingVsDensity

Initializing multi-output workflow...
NOTE: Optimization uses SCALED data for fair comparison across outputs
      Reporting includes normalized metrics (RMSE/std) for fair comparison

Fitting and saving data scalers...
  Scalers saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\models

--- Starting Workflow for: Linear ---
  Checking multi-output support for LinearRegression...
  → LinearRegression supports multi-output natively.
  No hyperparameters defined. Training model with default settings.
  Retraining the final model with the best hyperparameters...
  Final model training complete in 0.000 seconds.
  Best model saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\models\Linear_best_model.pkl

[I 2026-03-18 13:59:16,853] A new study created in memory with name: no-name-1729b553-6018-4cc8-9df0-f7a058aa0934

  Y-Y plot saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\plots\Linear_yy_plot.png

--- Starting Workflow for: RFR ---
  Checking multi-output support for RandomForestRegressor...
  → RandomForestRegressor supports multi-output natively.

  3%|▎         | 3/100 [00:00<00:12,  7.84it/s]

[I 2026-03-18 13:59:16,966] Trial 1 finished with values: [0.25864733747431545, 0.7387065593002964] and parameters: {'n_estimators': 133, 'max_depth': 141, 'min_samples_split': 8, 'min_samples_leaf': 13}.
[I 2026-03-18 13:59:16,978] Trial 0 finished with values: [0.2259864948341539, 0.7701976787297907] and parameters: {'n_estimators': 75, 'max_depth': 81, 'min_samples_split': 7, 'min_samples_leaf': 14}.
[I 2026-03-18 13:59:17,008] Trial 2 finished with values: [0.14813049215480822, 0.8493775980439405] and parameters: {'n_estimators': 79, 'max_depth': 24, 'min_samples_split': 16, 'min_samples_leaf': 11}.
[I 2026-03-18 13:59:17,011] Trial 8 finished with values: [0.19012642100498015, 0.8064869881568825] and parameters: {'n_estimators': 45, 'max_depth': 79, 'min_samples_split': 15, 'min_samples_leaf': 10}.

 11%|█         | 11/100 [00:00<00:02, 39.47it/s]

[I 2026-03-18 13:59:17,041] Trial 3 finished with values: [0.14952676691084743, 0.8478989331810398] and parameters: {'n_estimators': 30, 'max_depth': 48, 'min_samples_split': 20, 'min_samples_leaf': 18}.
[I 2026-03-18 13:59:17,042] Trial 4 finished with values: [0.14576240467833265, 0.8516098434186874] and parameters: {'n_estimators': 15, 'max_depth': 109, 'min_samples_split': 7, 'min_samples_leaf': 15}.
[I 2026-03-18 13:59:17,044] Trial 7 finished with values: [0.19426312158004158, 0.8021731029768192] and parameters: {'n_estimators': 79, 'max_depth': 149, 'min_samples_split': 7, 'min_samples_leaf': 8}.
[I 2026-03-18 13:59:17,063] Trial 5 finished with values: [0.14589735731371617, 0.8513397906124067] and parameters: {'n_estimators': 80, 'max_depth': 26, 'min_samples_split': 7, 'min_samples_leaf': 6}.
[I 2026-03-18 13:59:17,110] Trial 6 finished with values: [0.246097716859627, 0.750146854632748] and parameters: {'n_estimators': 127, 'max_depth': 105, 'min_samples_split': 8, 'min_samples_leaf': 17}.
[I 2026-03-18 13:59:17,134] Trial 11 finished with values: [0.11706788374671591, 0.880661511442986] and parameters: {'n_estimators': 50, 'max_depth': 68, 'min_samples_split': 20, 'min_samples_leaf': 15}.
[I 2026-03-18 13:59:17,147] Trial 10 finished with values: [0.11626539692917195, 0.8815620023063943] and parameters: {'n_estimators': 131, 'max_depth': 107, 'min_samples_split': 20, 'min_samples_leaf': 3}.
[I 2026-03-18 13:59:17,151] Trial 12 finished with values: [0.11704325398135082, 0.8806810834654504] and parameters: {'n_estimators': 57, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 1}.

[I 2026-03-18 13:59:17,212] Trial 15 finished with values: [0.2284760346984222, 0.7681562757814986] and parameters: {'n_estimators': 148, 'max_depth': 76, 'min_samples_split': 12, 'min_samples_leaf': 20}.
[I 2026-03-18 13:59:17,226] Trial 9 finished with values: [0.18473463726318234, 0.8131551922323942] and parameters: {'n_estimators': 69, 'max_depth': 19, 'min_samples_split': 18, 'min_samples_leaf': 16}.

[I 2026-03-18 13:59:17,228] Trial 18 finished with values: [0.21625227545414116, 0.7802585903966621] and parameters: {'n_estimators': 125, 'max_depth': 68, 'min_samples_split': 5, 'min_samples_leaf': 2}.
[I 2026-03-18 13:59:17,257] Trial 13 finished with values: [0.27959253663047173, 0.7162580062098713] and parameters: {'n_estimators': 111, 'max_depth': 145, 'min_samples_split': 14, 'min_samples_leaf': 20}.
[I 2026-03-18 13:59:17,273] Trial 20 finished with values: [0.2171860521722236, 0.779162185311429] and parameters: {'n_estimators': 36, 'max_depth': 51, 'min_samples_split': 4, 'min_samples_leaf': 17}.
[I 2026-03-18 13:59:17,325] Trial 16 finished with values: [0.24947249335823257, 0.7502935595846008] and parameters: {'n_estimators': 143, 'max_depth': 80, 'min_samples_split': 9, 'min_samples_leaf': 1}.
[I 2026-03-18 13:59:17,359] Trial 19 finished with values: [0.2276813297714965, 0.7682684954720156] and parameters: {'n_estimators': 27, 'max_depth': 130, 'min_samples_split': 10, 'min_samples_leaf': 20}.
[I 2026-03-18 13:59:17,362] Trial 14 finished with values: [0.18419171901353162, 0.8102476613533621] and parameters: {'n_estimators': 10, 'max_depth': 114, 'min_samples_split': 18, 'min_samples_leaf': 12}.
[I 2026-03-18 13:59:17,362] Trial 17 finished with values: [0.19954804011648714, 0.7990758070643645] and parameters: {'n_estimators': 10, 'max_depth': 144, 'min_samples_split': 12, 'min_samples_leaf': 19}.

 22%|██▏       | 22/100 [00:00<00:01, 41.07it/s]

[I 2026-03-18 13:59:17,373] Trial 21 finished with values: [0.1956613582644201, 0.8034352252411496] and parameters: {'n_estimators': 42, 'max_depth': 146, 'min_samples_split': 8, 'min_samples_leaf': 2}.
[I 2026-03-18 13:59:17,401] Trial 23 finished with values: [0.22913838508477924, 0.767057941838881] and parameters: {'n_estimators': 10, 'max_depth': 115, 'min_samples_split': 5, 'min_samples_leaf': 15}.

 31%|███       | 31/100 [00:00<00:01, 53.68it/s]

[I 2026-03-18 13:59:17,432] Trial 24 finished with values: [0.170195331323326, 0.8270692629788862] and parameters: {'n_estimators': 57, 'max_depth': 89, 'min_samples_split': 12, 'min_samples_leaf': 13}.
[I 2026-03-18 13:59:17,446] Trial 27 finished with values: [0.16915190071782363, 0.8276309534753544] and parameters: {'n_estimators': 65, 'max_depth': 126, 'min_samples_split': 19, 'min_samples_leaf': 2}.
[I 2026-03-18 13:59:17,448] Trial 22 finished with values: [0.16954455230935758, 0.827405986552734] and parameters: {'n_estimators': 66, 'max_depth': 105, 'min_samples_split': 7, 'min_samples_leaf': 20}.
[I 2026-03-18 13:59:17,455] Trial 26 finished with values: [0.16814801055553824, 0.829020681414178] and parameters: {'n_estimators': 111, 'max_depth': 108, 'min_samples_split': 19, 'min_samples_leaf': 14}.
[I 2026-03-18 13:59:17,465] Trial 25 finished with values: [0.16809136621347015, 0.8289963602558513] and parameters: {'n_estimators': 26, 'max_depth': 23, 'min_samples_split': 15, 'min_samples_leaf': 12}.
[I 2026-03-18 13:59:17,520] Trial 28 finished with values: [0.09325798677514238, 0.9049167659175108] and parameters: {'n_estimators': 53, 'max_depth': 56, 'min_samples_split': 3, 'min_samples_leaf': 1}.
[I 2026-03-18 13:59:17,530] Trial 29 finished with values: [0.2679808587829154, 0.7279855740815111] and parameters: {'n_estimators': 73, 'max_depth': 95, 'min_samples_split': 19, 'min_samples_leaf': 19}.
[I 2026-03-18 13:59:17,531] Trial 31 finished with values: [0.18351247884592176, 0.8133137235160198] and parameters: {'n_estimators': 63, 'max_depth': 142, 'min_samples_split': 20, 'min_samples_leaf': 7}.
[I 2026-03-18 13:59:17,562] Trial 33 finished with values: [0.1986598396902008, 0.7978207951419971] and parameters: {'n_estimators': 66, 'max_depth': 141, 'min_samples_split': 12, 'min_samples_leaf': 11}.

 33%|███▎      | 33/100 [00:00<00:01, 53.68it/s]

[I 2026-03-18 13:59:17,582] Trial 30 finished with values: [0.1890627855361933, 0.8077789518535017] and parameters: {'n_estimators': 120, 'max_depth': 143, 'min_samples_split': 8, 'min_samples_leaf': 10}.
[I 2026-03-18 13:59:17,603] Trial 32 finished with values: [0.18622438232917285, 0.8106978989699479] and parameters: {'n_estimators': 100, 'max_depth': 115, 'min_samples_split': 10, 'min_samples_leaf': 10}.

 41%|████      | 41/100 [00:00<00:01, 47.48it/s]

[I 2026-03-18 13:59:17,655] Trial 37 finished with values: [0.17961913888668993, 0.8175239504480079] and parameters: {'n_estimators': 53, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 9}.
[I 2026-03-18 13:59:17,655] Trial 34 finished with values: [0.1892076186601906, 0.8075138993355415] and parameters: {'n_estimators': 111, 'max_depth': 39, 'min_samples_split': 14, 'min_samples_leaf': 10}.
[I 2026-03-18 13:59:17,689] Trial 39 finished with values: [0.19902897267031042, 0.7976651724028547] and parameters: {'n_estimators': 34, 'max_depth': 32, 'min_samples_split': 12, 'min_samples_leaf': 11}.
[I 2026-03-18 13:59:17,689] Trial 36 finished with values: [0.22773197956336508, 0.7684874746177592] and parameters: {'n_estimators': 109, 'max_depth': 38, 'min_samples_split': 4, 'min_samples_leaf': 14}.
[I 2026-03-18 13:59:17,720] Trial 42 finished with values: [0.2128885812805202, 0.7834890530631897] and parameters: {'n_estimators': 29, 'max_depth': 149, 'min_samples_split': 18, 'min_samples_leaf': 12}.
[I 2026-03-18 13:59:17,739] Trial 41 finished with values: [0.2223186124285458, 0.7739650588976954] and parameters: {'n_estimators': 42, 'max_depth': 83, 'min_samples_split': 2, 'min_samples_leaf': 13}.
[I 2026-03-18 13:59:17,750] Trial 35 finished with values: [0.15035903663091202, 0.8469754020175972] and parameters: {'n_estimators': 127, 'max_depth': 47, 'min_samples_split': 7, 'min_samples_leaf': 6}.
[I 2026-03-18 13:59:17,751] Trial 45 finished with values: [0.1616183693680993, 0.8355538215936169] and parameters: {'n_estimators': 14, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 2}.

 43%|████▎     | 43/100 [00:00<00:01, 50.71it/s]

[I 2026-03-18 13:59:17,793] Trial 43 finished with values: [0.15886899913219388, 0.8384291785107608] and parameters: {'n_estimators': 72, 'max_depth': 120, 'min_samples_split': 2, 'min_samples_leaf': 7}.
[I 2026-03-18 13:59:17,824] Trial 38 finished with values: [0.18048266106901492, 0.8163472706945288] and parameters: {'n_estimators': 141, 'max_depth': 126, 'min_samples_split': 16, 'min_samples_leaf': 9}.

 47%|████▋     | 47/100 [00:01<00:01, 50.71it/s]

[I 2026-03-18 13:59:17,845] Trial 40 finished with values: [0.2718963626035717, 0.7237125194372872] and parameters: {'n_estimators': 146, 'max_depth': 28, 'min_samples_split': 7, 'min_samples_leaf': 19}.
[I 2026-03-18 13:59:17,851] Trial 47 finished with values: [0.17043017536951172, 0.8266057597327295] and parameters: {'n_estimators': 55, 'max_depth': 132, 'min_samples_split': 12, 'min_samples_leaf': 8}.
[I 2026-03-18 13:59:17,914] Trial 44 finished with values: [0.27201345384769887, 0.7237952254199849] and parameters: {'n_estimators': 131, 'max_depth': 137, 'min_samples_split': 6, 'min_samples_leaf': 19}.
[I 2026-03-18 13:59:17,956] Trial 46 finished with values: [0.1627619667693793, 0.8344250849908009] and parameters: {'n_estimators': 129, 'max_depth': 17, 'min_samples_split': 17, 'min_samples_leaf': 4}.

 50%|█████     | 50/100 [00:01<00:01, 42.80it/s]

[I 2026-03-18 13:59:17,980] Trial 49 finished with values: [0.1824361813019806, 0.814615487374658] and parameters: {'n_estimators': 95, 'max_depth': 103, 'min_samples_split': 19, 'min_samples_leaf': 9}.
[I 2026-03-18 13:59:17,998] Trial 51 finished with values: [0.14771315574950764, 0.8498835219234759] and parameters: {'n_estimators': 50, 'max_depth': 99, 'min_samples_split': 7, 'min_samples_leaf': 6}.
[I 2026-03-18 13:59:18,016] Trial 48 finished with values: [0.14948065668155489, 0.8479259436097715] and parameters: {'n_estimators': 138, 'max_depth': 30, 'min_samples_split': 15, 'min_samples_leaf': 1}.

 55%|█████▌    | 55/100 [00:01<00:01, 42.26it/s]

[I 2026-03-18 13:59:18,059] Trial 52 finished with values: [0.18064049951291547, 0.8161361502501305] and parameters: {'n_estimators': 81, 'max_depth': 114, 'min_samples_split': 5, 'min_samples_leaf': 9}.
[I 2026-03-18 13:59:18,072] Trial 50 finished with values: [0.20967579115172114, 0.7870608819261434] and parameters: {'n_estimators': 116, 'max_depth': 120, 'min_samples_split': 7, 'min_samples_leaf': 12}.
[I 2026-03-18 13:59:18,103] Trial 53 finished with values: [0.20920934225105423, 0.7873639449196913] and parameters: {'n_estimators': 97, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 12}.
[I 2026-03-18 13:59:18,103] Trial 55 finished with values: [0.22339726012655556, 0.7727762659795563] and parameters: {'n_estimators': 66, 'max_depth': 56, 'min_samples_split': 18, 'min_samples_leaf': 13}.
[I 2026-03-18 13:59:18,119] Trial 56 finished with values: [0.27951324644835573, 0.7163512487658273] and parameters: {'n_estimators': 61, 'max_depth': 52, 'min_samples_split': 7, 'min_samples_leaf': 20}.

 57%|█████▋    | 57/100 [00:01<00:01, 42.26it/s]

[I 2026-03-18 13:59:18,175] Trial 57 finished with values: [0.14737089186563543, 0.8499338869263833] and parameters: {'n_estimators': 97, 'max_depth': 96, 'min_samples_split': 13, 'min_samples_leaf': 5}.
[I 2026-03-18 13:59:18,176] Trial 54 finished with values: [0.2796734750958834, 0.7162396664996433] and parameters: {'n_estimators': 135, 'max_depth': 129, 'min_samples_split': 16, 'min_samples_leaf': 20}.

 62%|██████▏   | 62/100 [00:01<00:00, 38.03it/s]

[I 2026-03-18 13:59:18,267] Trial 61 finished with values: [0.23133357723485898, 0.7650417400538364] and parameters: {'n_estimators': 81, 'max_depth': 20, 'min_samples_split': 17, 'min_samples_leaf': 14}.
[I 2026-03-18 13:59:18,288] Trial 64 finished with values: [0.13185540311497362, 0.865423397566859] and parameters: {'n_estimators': 15, 'max_depth': 136, 'min_samples_split': 9, 'min_samples_leaf': 2}.
[I 2026-03-18 13:59:18,290] Trial 59 finished with values: [0.20920192408092766, 0.7872473083372057] and parameters: {'n_estimators': 140, 'max_depth': 101, 'min_samples_split': 16, 'min_samples_leaf': 12}.
[I 2026-03-18 13:59:18,311] Trial 58 finished with values: [0.16804560135408428, 0.8290304419814198] and parameters: {'n_estimators': 118, 'max_depth': 83, 'min_samples_split': 9, 'min_samples_leaf': 8}.
[I 2026-03-18 13:59:18,339] Trial 60 finished with values: [0.2630504742887033, 0.7327669472771914] and parameters: {'n_estimators': 146, 'max_depth': 129, 'min_samples_split': 13, 'min_samples_leaf': 18}.

 69%|██████▉   | 69/100 [00:01<00:00, 39.64it/s]

[I 2026-03-18 13:59:18,380] Trial 62 finished with values: [0.2528302890123652, 0.7432566114456698] and parameters: {'n_estimators': 136, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 17}.
[I 2026-03-18 13:59:18,387] Trial 66 finished with values: [0.2362108961175445, 0.7599610292434343] and parameters: {'n_estimators': 62, 'max_depth': 136, 'min_samples_split': 18, 'min_samples_leaf': 15}.
[I 2026-03-18 13:59:18,398] Trial 67 finished with values: [0.14739551069490792, 0.8499005781537046] and parameters: {'n_estimators': 55, 'max_depth': 31, 'min_samples_split': 14, 'min_samples_leaf': 2}.
[I 2026-03-18 13:59:18,408] Trial 63 finished with values: [0.1804592190310098, 0.8164716804290318] and parameters: {'n_estimators': 93, 'max_depth': 62, 'min_samples_split': 3, 'min_samples_leaf': 9}.
[I 2026-03-18 13:59:18,418] Trial 65 finished with values: [0.28139482730708265, 0.7145983433128913] and parameters: {'n_estimators': 109, 'max_depth': 22, 'min_samples_split': 12, 'min_samples_leaf': 20}.
[I 2026-03-18 13:59:18,426] Trial 69 finished with values: [0.2296501556406923, 0.7667345945046575] and parameters: {'n_estimators': 46, 'max_depth': 78, 'min_samples_split': 9, 'min_samples_leaf': 14}.
[I 2026-03-18 13:59:18,449] Trial 72 finished with values: [0.18996821794693622, 0.8066304899112685] and parameters: {'n_estimators': 28, 'max_depth': 96, 'min_samples_split': 20, 'min_samples_leaf': 9}.

 73%|███████▎  | 73/100 [00:01<00:00, 45.90it/s]

[I 2026-03-18 13:59:18,476] Trial 68 finished with values: [0.2540572930304183, 0.742073110611731] and parameters: {'n_estimators': 95, 'max_depth': 119, 'min_samples_split': 7, 'min_samples_leaf': 17}.
[I 2026-03-18 13:59:18,512] Trial 75 finished with values: [0.2643518626721481, 0.7313913712224689] and parameters: {'n_estimators': 45, 'max_depth': 37, 'min_samples_split': 7, 'min_samples_leaf': 18}.
[I 2026-03-18 13:59:18,529] Trial 71 finished with values: [0.12513391708157814, 0.8723862886493332] and parameters: {'n_estimators': 59, 'max_depth': 88, 'min_samples_split': 2, 'min_samples_leaf': 4}.
[I 2026-03-18 13:59:18,555] Trial 70 finished with values: [0.1696547893439348, 0.8272854699749835] and parameters: {'n_estimators': 93, 'max_depth': 77, 'min_samples_split': 16, 'min_samples_leaf': 8}.

[I 2026-03-18 13:59:18,585] Trial 74 finished with values: [0.27301731875746166, 0.7226190201619789] and parameters: {'n_estimators': 120, 'max_depth': 40, 'min_samples_split': 18, 'min_samples_leaf': 19}.
[I 2026-03-18 13:59:18,607] Trial 80 finished with values: [0.1788510275714688, 0.817999010071133] and parameters: {'n_estimators': 12, 'max_depth': 98, 'min_samples_split': 3, 'min_samples_leaf': 8}.
[I 2026-03-18 13:59:18,623] Trial 79 finished with values: [0.21767664121290417, 0.7780992471344612] and parameters: {'n_estimators': 29, 'max_depth': 149, 'min_samples_split': 18, 'min_samples_leaf': 12}.
[I 2026-03-18 13:59:18,638] Trial 76 finished with values: [0.21972310259630415, 0.7767369999577137] and parameters: {'n_estimators': 94, 'max_depth': 131, 'min_samples_split': 10, 'min_samples_leaf': 13}.
[I 2026-03-18 13:59:18,645] Trial 82 finished with values: [0.15197417853699932, 0.845061959247815] and parameters: {'n_estimators': 14, 'max_depth': 144, 'min_samples_split': 12, 'min_samples_leaf': 2}.

[I 2026-03-18 13:59:18,655] Trial 83 finished with values: [0.22371880522824253, 0.7718921745851884] and parameters: {'n_estimators': 10, 'max_depth': 144, 'min_samples_split': 12, 'min_samples_leaf': 12}.
[I 2026-03-18 13:59:18,676] Trial 73 finished with values: [0.14030423563475, 0.8571736109083294] and parameters: {'n_estimators': 142, 'max_depth': 28, 'min_samples_split': 13, 'min_samples_leaf': 1}.
[I 2026-03-18 13:59:18,686] Trial 78 finished with values: [0.2300915587334949, 0.766283924657849] and parameters: {'n_estimators': 107, 'max_depth': 73, 'min_samples_split': 19, 'min_samples_leaf': 14}.
[I 2026-03-18 13:59:18,701] Trial 81 finished with values: [0.24678205573992695, 0.7493194822251418] and parameters: {'n_estimators': 55, 'max_depth': 132, 'min_samples_split': 11, 'min_samples_leaf': 16}.
[I 2026-03-18 13:59:18,707] Trial 84 finished with values: [0.20731564970138963, 0.789225518958137] and parameters: {'n_estimators': 34, 'max_depth': 32, 'min_samples_split': 20, 'min_samples_leaf': 11}.
[I 2026-03-18 13:59:18,717] Trial 86 finished with values: [0.13891502246408072, 0.8585336731723949] and parameters: {'n_estimators': 34, 'max_depth': 70, 'min_samples_split': 12, 'min_samples_leaf': 2}.
[I 2026-03-18 13:59:18,721] Trial 88 finished with values: [0.24723570414507073, 0.7481219520645304] and parameters: {'n_estimators': 15, 'max_depth': 109, 'min_samples_split': 20, 'min_samples_leaf': 15}.
[I 2026-03-18 13:59:18,733] Trial 77 finished with values: [0.13681385975580806, 0.860709445946398] and parameters: {'n_estimators': 148, 'max_depth': 107, 'min_samples_split': 12, 'min_samples_leaf': 3}.

 88%|████████▊ | 88/100 [00:01<00:00, 58.11it/s]

[I 2026-03-18 13:59:18,764] Trial 91 finished with values: [0.16328332471564436, 0.8338477891307008] and parameters: {'n_estimators': 26, 'max_depth': 26, 'min_samples_split': 15, 'min_samples_leaf': 6}.
[I 2026-03-18 13:59:18,782] Trial 92 finished with values: [0.12375336499392595, 0.8741434468887782] and parameters: {'n_estimators': 14, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 2}.

 94%|█████████▍| 94/100 [00:02<00:00, 47.57it/s]

[I 2026-03-18 13:59:18,852] Trial 87 finished with values: [0.16278617202901938, 0.8344583671630404] and parameters: {'n_estimators': 114, 'max_depth': 54, 'min_samples_split': 17, 'min_samples_leaf': 4}.
[I 2026-03-18 13:59:18,876] Trial 85 finished with values: [0.11507531674242562, 0.88268375996653] and parameters: {'n_estimators': 131, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 1}.
[I 2026-03-18 13:59:18,893] Trial 89 finished with values: [0.10888223424175705, 0.8888757051977194] and parameters: {'n_estimators': 111, 'max_depth': 105, 'min_samples_split': 7, 'min_samples_leaf': 1}.
[I 2026-03-18 13:59:18,915] Trial 93 finished with values: [0.12524009263187116, 0.8722787112011137] and parameters: {'n_estimators': 80, 'max_depth': 47, 'min_samples_split': 7, 'min_samples_leaf': 4}.
[I 2026-03-18 13:59:18,944] Trial 97 finished with values: [0.11843832618664152, 0.8790613803389133] and parameters: {'n_estimators': 18, 'max_depth': 105, 'min_samples_split': 7, 'min_samples_leaf': 1}.
[I 2026-03-18 13:59:18,951] Trial 90 finished with values: [0.14544512740779286, 0.8520076148608317] and parameters: {'n_estimators': 149, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 6}.

100%|██████████| 100/100 [00:02<00:00, 46.28it/s]

[I 2026-03-18 13:59:18,954] Trial 99 finished with values: [0.2548809421811833, 0.7410969772683484] and parameters: {'n_estimators': 23, 'max_depth': 51, 'min_samples_split': 4, 'min_samples_leaf': 17}.
[I 2026-03-18 13:59:18,955] Trial 96 finished with values: [0.18531588722433795, 0.8112753475827941] and parameters: {'n_estimators': 36, 'max_depth': 51, 'min_samples_split': 20, 'min_samples_leaf': 7}.
[I 2026-03-18 13:59:18,980] Trial 98 finished with values: [0.17058635437264763, 0.8260939074377213] and parameters: {'n_estimators': 55, 'max_depth': 132, 'min_samples_split': 12, 'min_samples_leaf': 8}.
[I 2026-03-18 13:59:18,985] Trial 94 finished with values: [0.28032670874763516, 0.715370122884894] and parameters: {'n_estimators': 111, 'max_depth': 145, 'min_samples_split': 20, 'min_samples_leaf': 20}.
[I 2026-03-18 13:59:19,015] Trial 95 finished with values: [0.18940604963438654, 0.8072482558070231] and parameters: {'n_estimators': 129, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 10}.
  Hyperparameter optimization completed in 2.164 seconds.
  Selected Trial #28 with Mean MSE=0.0933, Mean R2=0.9049
  Retraining the final model with the best hyperparameters...

c:\Users\trippr5118\Documents\Research\resource-allocation\core\armote_multi_output.py:416: ExperimentalWarning: optuna.visualization.matplotlib._pareto_front.plot_pareto_front is experimental (supported from v2.8.0). The interface can change in the future.
  ax = vis.plot_pareto_front(study, target_names=target_names)

  Final model training complete in 0.065 seconds.
  Optuna study saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\studies\RFR_study.pkl

c:\Users\trippr5118\Documents\Research\resource-allocation\core\armote_multi_output.py:425: ExperimentalWarning: optuna.visualization.matplotlib._optimization_history.plot_optimization_history is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_optimization_history(
c:\Users\trippr5118\Documents\Research\resource-allocation\core\armote_multi_output.py:436: ExperimentalWarning: optuna.visualization.matplotlib._optimization_history.plot_optimization_history is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_optimization_history(
c:\Users\trippr5118\Documents\Research\resource-allocation\core\armote_multi_output.py:447: ExperimentalWarning: optuna.visualization.matplotlib._param_importances.plot_param_importances is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_param_importances(study)

  Optuna plots for RFR saved in 'ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\plots' directory.
  Best model saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\models\RFR_best_model.pkl
  Y-Y plot saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\plots\RFR_yy_plot.png

--- Workflow Complete ---
✓ Results summary saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\results.csv
✓ Detailed results saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\results_detailed.txt
✓ Models saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\models
✓ Plots saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\plots
✓ Studies saved to: ground_truth_models/TiVNbMoHfTaW-MeltingVsDensity\studies
    Model  Optimization Time (s)  Retraining Time (s)  \
0  Linear                  0.000                0.000
1     RFR                  2.164                0.065

                                         Best Params Train R2 (Per-Output)  \
0                                                 {}         [1.0, 0.9153]
1  {'n_estimators': 53, 'max_depth': 56, 'min_sam...      [0.9813, 0.9849]

  Train MSE (Per-Output) Train MAE (Per-Output) Test R2 (Per-Output)  \
0        [0.0, 0.042704]        [0.0, 0.160963]        [1.0, 0.9243]
1  [94.088107, 0.007608]   [7.706075, 0.068668]     [0.8909, 0.9286]

    Test MSE (Per-Output)  Test MAE (Per-Output)
0          [0.0, 0.03743]        [0.0, 0.152556]
1  [539.165465, 0.035326]  [19.540713, 0.152162]

In [8]:
# Path to your Excel training data
TRAINING_XLSX = "data/1000_refractory_alloy_calphad_modeled_data.xlsx"

# Input columns must match the component labels / order used in DesignSpace
INPUT_COLS = ["Ti", "V", "Nb", "Mo", "Hf", "Ta", "W"]

# Target columns in your Excel sheet
TARGET_COLS = [
    "PROP RT Therm Cond (W/(mK))",
    "Sconf",
]

# Where to save the optimized models, scalers, plots, and optimization studies and results
OUTPUT_DIR = "ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond"
os.makedirs(OUTPUT_DIR, exist_ok=True)

MODELS_PATH = os.path.join(OUTPUT_DIR, "models")
PLOTS_PATH = os.path.join(OUTPUT_DIR, "plots")
STUDIES_PATH = os.path.join(OUTPUT_DIR, "studies")
RESULTS_PATH = OUTPUT_DIR

In [9]:
# If your data is on a specific sheet, pass sheet_name="Sheet1" (or the right name).
df = pd.read_excel(TRAINING_XLSX)  # , sheet_name="Sheet1"
df.head()

,Unnamed: 0,Ti,V,Nb,Mo,Hf,Ta,W,System Type,Unnamed: 0.2,...,Atomic Planar Density_Var,C_11_Avg,C_11_Var,C_12_Avg,C_12_Var,C'_Avg,C'_Var,Bulk Modulus (GPa)_Avg,Bulk Modulus (GPa)_Var,Pugh Ratio
0,500,0.05,0.000,0.575,0.100,0.0,0.225,0.050,17,77984,...,5.178468,16.650,39.770938,36.150,94.433191,-9.7500,31.358611,186.75,37.972852,3.132075
1,682,0.10,0.000,0.475,0.100,0.0,0.325,0.000,58,96328,...,5.697076,22.800,45.777287,41.100,95.001526,-9.1500,31.652843,179.75,30.289231,3.160440
2,809,0.05,0.000,0.600,0.050,0.0,0.225,0.075,17,80189,...,4.271883,11.400,34.318217,20.550,70.249181,-4.5750,22.844734,187.25,41.652581,3.195392
3,139,0.00,0.050,0.600,0.075,0.0,0.200,0.075,16,76428,...,5.118709,8.875,27.714786,36.350,96.610183,-13.7375,36.451507,190.50,38.791107,3.173678
4,766,0.05,0.025,0.550,0.125,0.0,0.250,0.000,28,93443,...,5.914301,19.775,41.875104,50.425,108.592792,-15.3250,38.319471,181.75,26.822332,3.215391

In [10]:
# Extract inputs (X) and targets (y)
X_raw = df[INPUT_COLS]
y_raw = df[TARGET_COLS]

print("X_raw shape:", X_raw.shape)
print("y_raw shape:", y_raw.shape)

X_raw shape: (1000, 7)
y_raw shape: (1000, 2)

In [11]:
# Define models
models = {
    "Linear": LinearRegression(),
    "RFR": RandomForestRegressor()
}

In [12]:
# Define hyperparameter spaces for optimization
param_spaces = {
    "RFR": {
        "n_estimators": ('int', 10, 150),   # Number of trees
        "max_depth": ('int', 10, 150),         # Maximum depth of trees
        "min_samples_split": ('int', 2, 20), # Minimum number of samples required to split an internal node
        "min_samples_leaf": ('int', 1, 20)   # Minimum number of samples required to be at a leaf node
    }
}

In [13]:
# Import the run_workflow function from workflow.py
from core.armote_multi_output import run_workflow

# Define output labels
output_labels = ['K (W/(m·K))', 'ΔSᶜᵒⁿᶠⁱᵍ (R)']

# Define the folder dictionary
folder_dict = {
    'models': MODELS_PATH,
    'plots': PLOTS_PATH,
    'studies': STUDIES_PATH,
    'results': RESULTS_PATH
    }

# Run the workflow
results_df = run_workflow(X_raw, y_raw, models, param_spaces, output_labels=output_labels, folder_dict=folder_dict)

# Display the results DataFrame
print(results_df)

Setting up output folders...
✓ Models folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\TiVNbMoHfTaW_Max_S_Max_TCond\models
✓ Plots folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\TiVNbMoHfTaW_Max_S_Max_TCond\plots
✓ Studies folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\TiVNbMoHfTaW_Max_S_Max_TCond\studies
✓ Results folder ready: c:\Users\shakt\Documents\gitrepo\resource-allocation\ground_truth_models\TiVNbMoHfTaW_Max_S_Max_TCond

Initializing multi-output workflow...
NOTE: Optimization uses SCALED data for fair comparison across outputs
      Reporting includes normalized metrics (RMSE/std) for fair comparison

Fitting and saving data scalers...
  Scalers saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\models

--- Starting Workflow for: Linear ---
  Checking multi-output support for LinearRegression...
  → LinearRegression supports multi-output natively.
  No hyperparameters defined. Training model with default settings.
  Retraining the final model with the best hyperparameters...
  Final model training complete in 0.001 seconds.
  Best model saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\models\Linear_best_model.pkl

[I 2026-02-03 11:28:43,689] A new study created in memory with name: no-name-e71b6dff-bac5-4bfc-98b2-a4a24d7e7638

  Y-Y plot saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\plots\Linear_yy_plot.png

--- Starting Workflow for: RFR ---
  Checking multi-output support for RandomForestRegressor...
  → RandomForestRegressor supports multi-output natively.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-02-03 11:28:44,400] Trial 0 finished with values: [0.16521056366215547, 0.8337993376652723] and parameters: {'n_estimators': 101, 'max_depth': 105, 'min_samples_split': 15, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:44,429] Trial 1 finished with values: [0.1660273508086155, 0.8336180486232445] and parameters: {'n_estimators': 147, 'max_depth': 63, 'min_samples_split': 18, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:45,462] Trial 7 finished with values: [0.11714934974549147, 0.8819880855948823] and parameters: {'n_estimators': 30, 'max_depth': 126, 'min_samples_split': 9, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:45,478] Trial 2 finished with values: [0.1651942842243716, 0.8333636254599363] and parameters: {'n_estimators': 10, 'max_depth': 95, 'min_samples_split': 19, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:46,259] Trial 11 finished with values: [0.1180223685380694, 0.881168609567459] and parameters: {'n_estimators': 145, 'max_depth': 111, 'min_samples_split': 20, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:46,353] Trial 3 finished with values: [0.12926730124006267, 0.8693087998533866] and parameters: {'n_estimators': 106, 'max_depth': 145, 'min_samples_split': 15, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:46,480] Trial 10 finished with values: [0.11848765449049985, 0.8806345435761852] and parameters: {'n_estimators': 41, 'max_depth': 32, 'min_samples_split': 20, 'min_samples_leaf': 11}.
[I 2026-02-03 11:28:46,545] Trial 9 finished with values: [0.11766372476507872, 0.8815500912070275] and parameters: {'n_estimators': 143, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:46,669] Trial 8 finished with values: [0.11701499057489115, 0.8822014907925636] and parameters: {'n_estimators': 147, 'max_depth': 40, 'min_samples_split': 20, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:46,762] Trial 13 finished with values: [0.11697252642527071, 0.8822552871035769] and parameters: {'n_estimators': 89, 'max_depth': 100, 'min_samples_split': 6, 'min_samples_leaf': 12}.
[I 2026-02-03 11:28:46,826] Trial 5 finished with values: [0.11831568498527154, 0.8808756322358822] and parameters: {'n_estimators': 95, 'max_depth': 19, 'min_samples_split': 11, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:47,170] Trial 4 finished with values: [0.11783944863456845, 0.8812996563568299] and parameters: {'n_estimators': 86, 'max_depth': 130, 'min_samples_split': 9, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:47,603] Trial 17 finished with values: [0.20121982680164402, 0.7974459293792714] and parameters: {'n_estimators': 13, 'max_depth': 56, 'min_samples_split': 5, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:47,695] Trial 14 finished with values: [0.1164801773788107, 0.8827249637533816] and parameters: {'n_estimators': 122, 'max_depth': 147, 'min_samples_split': 3, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:47,793] Trial 15 finished with values: [0.11901570564773623, 0.8801058507432786] and parameters: {'n_estimators': 145, 'max_depth': 107, 'min_samples_split': 10, 'min_samples_leaf': 1}.
[I 2026-02-03 11:28:47,853] Trial 6 finished with values: [0.11928430215206302, 0.8798977180101195] and parameters: {'n_estimators': 42, 'max_depth': 100, 'min_samples_split': 19, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:47,947] Trial 12 finished with values: [0.1194328307577813, 0.8797341301540971] and parameters: {'n_estimators': 149, 'max_depth': 17, 'min_samples_split': 17, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:48,153] Trial 18 finished with values: [0.1366600890626667, 0.8623826822799934] and parameters: {'n_estimators': 126, 'max_depth': 121, 'min_samples_split': 3, 'min_samples_leaf': 6}.
[I 2026-02-03 11:28:48,166] Trial 19 finished with values: [0.14060679706844104, 0.8582404790003728] and parameters: {'n_estimators': 33, 'max_depth': 58, 'min_samples_split': 17, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:48,273] Trial 20 finished with values: [0.10932688331821774, 0.8899524353245608] and parameters: {'n_estimators': 83, 'max_depth': 51, 'min_samples_split': 7, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:48,662] Trial 23 finished with values: [0.1648380404286007, 0.8340686963794826] and parameters: {'n_estimators': 78, 'max_depth': 122, 'min_samples_split': 5, 'min_samples_leaf': 10}.
[I 2026-02-03 11:28:48,898] Trial 16 finished with values: [0.12546511665834065, 0.8736197266861655] and parameters: {'n_estimators': 139, 'max_depth': 150, 'min_samples_split': 6, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:48,960] Trial 26 finished with values: [0.1345896846490465, 0.8642943726262334] and parameters: {'n_estimators': 38, 'max_depth': 80, 'min_samples_split': 12, 'min_samples_leaf': 6}.
[I 2026-02-03 11:28:48,993] Trial 21 finished with values: [0.10140121803232845, 0.897977177658424] and parameters: {'n_estimators': 139, 'max_depth': 31, 'min_samples_split': 4, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:49,038] Trial 24 finished with values: [0.1738074950701986, 0.8249914656124535] and parameters: {'n_estimators': 111, 'max_depth': 41, 'min_samples_split': 12, 'min_samples_leaf': 11}.
[I 2026-02-03 11:28:49,054] Trial 25 finished with values: [0.20851848418891583, 0.7906221515228402] and parameters: {'n_estimators': 32, 'max_depth': 115, 'min_samples_split': 12, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:49,100] Trial 28 finished with values: [0.19748952604833483, 0.8013591900276591] and parameters: {'n_estimators': 17, 'max_depth': 78, 'min_samples_split': 17, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:49,117] Trial 30 finished with values: [0.16212194598668245, 0.8367884380568146] and parameters: {'n_estimators': 13, 'max_depth': 83, 'min_samples_split': 12, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:49,396] Trial 22 finished with values: [0.11784764352243364, 0.8813030315175322] and parameters: {'n_estimators': 90, 'max_depth': 102, 'min_samples_split': 10, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:49,447] Trial 27 finished with values: [0.2151178399548357, 0.7841717873277063] and parameters: {'n_estimators': 51, 'max_depth': 54, 'min_samples_split': 4, 'min_samples_leaf': 20}.
[I 2026-02-03 11:28:49,647] Trial 31 finished with values: [0.1580126340553305, 0.8408784930420523] and parameters: {'n_estimators': 79, 'max_depth': 51, 'min_samples_split': 2, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:49,759] Trial 35 finished with values: [0.1439672801472181, 0.8549741742859156] and parameters: {'n_estimators': 43, 'max_depth': 63, 'min_samples_split': 5, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:49,940] Trial 32 finished with values: [0.1589319528094217, 0.8398760375519266] and parameters: {'n_estimators': 48, 'max_depth': 107, 'min_samples_split': 11, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:49,967] Trial 34 finished with values: [0.20768167040731084, 0.7913169786726402] and parameters: {'n_estimators': 34, 'max_depth': 145, 'min_samples_split': 2, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:50,023] Trial 29 finished with values: [0.19301667937199038, 0.8056961598922745] and parameters: {'n_estimators': 117, 'max_depth': 85, 'min_samples_split': 12, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:50,038] Trial 36 finished with values: [0.1806561635733857, 0.8181836613505762] and parameters: {'n_estimators': 84, 'max_depth': 13, 'min_samples_split': 19, 'min_samples_leaf': 12}.
[I 2026-02-03 11:28:50,100] Trial 39 finished with values: [0.127810220007651, 0.8714225048308432] and parameters: {'n_estimators': 10, 'max_depth': 147, 'min_samples_split': 10, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:50,151] Trial 38 finished with values: [0.20480762142964135, 0.7940100682697576] and parameters: {'n_estimators': 66, 'max_depth': 42, 'min_samples_split': 12, 'min_samples_leaf': 18}.
[I 2026-02-03 11:28:50,194] Trial 40 finished with values: [0.14438315986278003, 0.8545735386194545] and parameters: {'n_estimators': 129, 'max_depth': 30, 'min_samples_split': 20, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:50,256] Trial 33 finished with values: [0.14691108282589602, 0.8520896004894178] and parameters: {'n_estimators': 76, 'max_depth': 138, 'min_samples_split': 19, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:50,398] Trial 41 finished with values: [0.13733880333767376, 0.8617451221096741] and parameters: {'n_estimators': 30, 'max_depth': 99, 'min_samples_split': 18, 'min_samples_leaf': 1}.
[I 2026-02-03 11:28:50,414] Trial 37 finished with values: [0.14498815381978583, 0.8540068886778819] and parameters: {'n_estimators': 69, 'max_depth': 123, 'min_samples_split': 5, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:50,664] Trial 43 finished with values: [0.1335183182243874, 0.8654738378650115] and parameters: {'n_estimators': 53, 'max_depth': 33, 'min_samples_split': 14, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:50,741] Trial 46 finished with values: [0.1889288276806993, 0.8099431099051475] and parameters: {'n_estimators': 26, 'max_depth': 54, 'min_samples_split': 20, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:50,804] Trial 44 finished with values: [0.1500904246824611, 0.8488250284912346] and parameters: {'n_estimators': 84, 'max_depth': 10, 'min_samples_split': 18, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:50,819] Trial 45 finished with values: [0.15985688808934675, 0.8390513719150754] and parameters: {'n_estimators': 25, 'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:50,928] Trial 42 finished with values: [0.21221325099837074, 0.7869096288680019] and parameters: {'n_estimators': 116, 'max_depth': 109, 'min_samples_split': 11, 'min_samples_leaf': 20}.
[I 2026-02-03 11:28:50,990] Trial 47 finished with values: [0.18638861503487994, 0.8123117192924194] and parameters: {'n_estimators': 35, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:51,117] Trial 50 finished with values: [0.1527627471520188, 0.8460879588409884] and parameters: {'n_estimators': 31, 'max_depth': 18, 'min_samples_split': 20, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:51,134] Trial 48 finished with values: [0.21280584974239142, 0.7863061710226049] and parameters: {'n_estimators': 51, 'max_depth': 55, 'min_samples_split': 2, 'min_samples_leaf': 20}.
[I 2026-02-03 11:28:51,164] Trial 52 finished with values: [0.19612652936889155, 0.8026208783296358] and parameters: {'n_estimators': 23, 'max_depth': 90, 'min_samples_split': 9, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:51,195] Trial 53 finished with values: [0.19217259911254095, 0.8064837568839263] and parameters: {'n_estimators': 28, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 14}.
[I 2026-02-03 11:28:51,259] Trial 49 finished with values: [0.17983145358981245, 0.8190383692643511] and parameters: {'n_estimators': 69, 'max_depth': 79, 'min_samples_split': 16, 'min_samples_leaf': 12}.
[I 2026-02-03 11:28:51,539] Trial 56 finished with values: [0.13094840157964088, 0.8679541374990457] and parameters: {'n_estimators': 38, 'max_depth': 136, 'min_samples_split': 12, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:51,572] Trial 54 finished with values: [0.1477249297759562, 0.8510747297116931] and parameters: {'n_estimators': 48, 'max_depth': 56, 'min_samples_split': 15, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:51,635] Trial 55 finished with values: [0.11781392319446012, 0.8813084293053084] and parameters: {'n_estimators': 57, 'max_depth': 40, 'min_samples_split': 9, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:51,863] Trial 51 finished with values: [0.21353192249048308, 0.7856988346191309] and parameters: {'n_estimators': 114, 'max_depth': 59, 'min_samples_split': 19, 'min_samples_leaf': 20}.
[I 2026-02-03 11:28:51,982] Trial 57 finished with values: [0.17823255125876997, 0.8205619935702352] and parameters: {'n_estimators': 137, 'max_depth': 116, 'min_samples_split': 2, 'min_samples_leaf': 12}.
[I 2026-02-03 11:28:52,185] Trial 61 finished with values: [0.15658364998443608, 0.842181754508354] and parameters: {'n_estimators': 37, 'max_depth': 45, 'min_samples_split': 15, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:52,215] Trial 58 finished with values: [0.2022454943742468, 0.7965820034279087] and parameters: {'n_estimators': 130, 'max_depth': 34, 'min_samples_split': 17, 'min_samples_leaf': 18}.
[I 2026-02-03 11:28:52,263] Trial 59 finished with values: [0.10380368033529322, 0.8954599086844958] and parameters: {'n_estimators': 66, 'max_depth': 27, 'min_samples_split': 3, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:52,355] Trial 60 finished with values: [0.14091270553478133, 0.8580959297088164] and parameters: {'n_estimators': 57, 'max_depth': 53, 'min_samples_split': 16, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:52,525] Trial 62 finished with values: [0.20392943507646333, 0.794875729971401] and parameters: {'n_estimators': 108, 'max_depth': 41, 'min_samples_split': 13, 'min_samples_leaf': 18}.
[I 2026-02-03 11:28:52,686] Trial 63 finished with values: [0.19732361449288408, 0.8016077430669395] and parameters: {'n_estimators': 113, 'max_depth': 104, 'min_samples_split': 3, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:52,905] Trial 65 finished with values: [0.1483973083584819, 0.8507215669731252] and parameters: {'n_estimators': 143, 'max_depth': 32, 'min_samples_split': 20, 'min_samples_leaf': 11}.
[I 2026-02-03 11:28:52,992] Trial 66 finished with values: [0.10823676339682595, 0.8910435114632035] and parameters: {'n_estimators': 90, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:53,140] Trial 64 finished with values: [0.12721424422765096, 0.8711587879087105] and parameters: {'n_estimators': 42, 'max_depth': 100, 'min_samples_split': 19, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:53,282] Trial 70 finished with values: [0.18612300615377425, 0.8126936764070745] and parameters: {'n_estimators': 26, 'max_depth': 102, 'min_samples_split': 10, 'min_samples_leaf': 13}.
[I 2026-02-03 11:28:53,339] Trial 67 finished with values: [0.19459246905882632, 0.8040960386681565] and parameters: {'n_estimators': 106, 'max_depth': 99, 'min_samples_split': 15, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:53,455] Trial 69 finished with values: [0.158207450515118, 0.8406349641464559] and parameters: {'n_estimators': 79, 'max_depth': 51, 'min_samples_split': 12, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:53,630] Trial 68 finished with values: [0.20118904912741464, 0.7975717794030244] and parameters: {'n_estimators': 143, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:53,764] Trial 74 finished with values: [0.15946135245054563, 0.8395111184202397] and parameters: {'n_estimators': 30, 'max_depth': 97, 'min_samples_split': 17, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:53,827] Trial 71 finished with values: [0.19358067178352617, 0.8052242634577604] and parameters: {'n_estimators': 106, 'max_depth': 24, 'min_samples_split': 15, 'min_samples_leaf': 15}.
[I 2026-02-03 11:28:54,063] Trial 76 finished with values: [0.19675396456231248, 0.8019288375775439] and parameters: {'n_estimators': 31, 'max_depth': 111, 'min_samples_split': 14, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:54,156] Trial 75 finished with values: [0.1524437138037969, 0.8464242671162326] and parameters: {'n_estimators': 83, 'max_depth': 126, 'min_samples_split': 7, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:54,299] Trial 72 finished with values: [0.151635714691931, 0.8472050747827226] and parameters: {'n_estimators': 147, 'max_depth': 146, 'min_samples_split': 20, 'min_samples_leaf': 6}.
[I 2026-02-03 11:28:54,315] Trial 73 finished with values: [0.12430968805105036, 0.8748000482246105] and parameters: {'n_estimators': 147, 'max_depth': 147, 'min_samples_split': 11, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:54,831] Trial 78 finished with values: [0.2000707922069825, 0.798783077695383] and parameters: {'n_estimators': 143, 'max_depth': 95, 'min_samples_split': 19, 'min_samples_leaf': 17}.
[I 2026-02-03 11:28:54,861] Trial 81 finished with values: [0.1362677802374718, 0.8626747531522915] and parameters: {'n_estimators': 38, 'max_depth': 40, 'min_samples_split': 12, 'min_samples_leaf': 6}.
[I 2026-02-03 11:28:54,876] Trial 79 finished with values: [0.19636277805131105, 0.8025334080494065] and parameters: {'n_estimators': 89, 'max_depth': 36, 'min_samples_split': 18, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:54,955] Trial 77 finished with values: [0.1516999737193613, 0.8471836629655174] and parameters: {'n_estimators': 139, 'max_depth': 31, 'min_samples_split': 12, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:55,328] Trial 82 finished with values: [0.14292600736772343, 0.8559257949137159] and parameters: {'n_estimators': 106, 'max_depth': 146, 'min_samples_split': 12, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:55,391] Trial 83 finished with values: [0.14363029002369548, 0.8554392862048225] and parameters: {'n_estimators': 69, 'max_depth': 123, 'min_samples_split': 5, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:55,393] Trial 84 finished with values: [0.20805714398596198, 0.7908931541322939] and parameters: {'n_estimators': 63, 'max_depth': 147, 'min_samples_split': 15, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:55,438] Trial 80 finished with values: [0.12596694231652586, 0.8732012360732799] and parameters: {'n_estimators': 139, 'max_depth': 62, 'min_samples_split': 6, 'min_samples_leaf': 5}.
[I 2026-02-03 11:28:55,484] Trial 85 finished with values: [0.19511014839812918, 0.8035890559303633] and parameters: {'n_estimators': 69, 'max_depth': 147, 'min_samples_split': 5, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:55,729] Trial 86 finished with values: [0.10016521771410716, 0.8992063859951255] and parameters: {'n_estimators': 84, 'max_depth': 31, 'min_samples_split': 4, 'min_samples_leaf': 2}.
[I 2026-02-03 11:28:55,858] Trial 88 finished with values: [0.13220191831814265, 0.8668345035600591] and parameters: {'n_estimators': 53, 'max_depth': 33, 'min_samples_split': 14, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:55,903] Trial 89 finished with values: [0.15985249989090805, 0.8390154475300552] and parameters: {'n_estimators': 48, 'max_depth': 47, 'min_samples_split': 11, 'min_samples_leaf': 9}.
[I 2026-02-03 11:28:56,236] Trial 90 finished with values: [0.14536571198408962, 0.8535327286873127] and parameters: {'n_estimators': 71, 'max_depth': 147, 'min_samples_split': 19, 'min_samples_leaf': 3}.
[I 2026-02-03 11:28:56,397] Trial 93 finished with values: [0.15266121369472407, 0.8462852298708141] and parameters: {'n_estimators': 38, 'max_depth': 80, 'min_samples_split': 20, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:56,532] Trial 87 finished with values: [0.14258823524761272, 0.8563944349798804] and parameters: {'n_estimators': 138, 'max_depth': 130, 'min_samples_split': 5, 'min_samples_leaf': 7}.
[I 2026-02-03 11:28:56,677] Trial 92 finished with values: [0.1958013328530233, 0.8029957075582633] and parameters: {'n_estimators': 145, 'max_depth': 33, 'min_samples_split': 14, 'min_samples_leaf': 16}.
[I 2026-02-03 11:28:57,102] Trial 97 finished with values: [0.1443421468921258, 0.854629100205098] and parameters: {'n_estimators': 74, 'max_depth': 126, 'min_samples_split': 18, 'min_samples_leaf': 4}.
[I 2026-02-03 11:28:57,258] Trial 91 finished with values: [0.1511887425085771, 0.8476895692237638] and parameters: {'n_estimators': 143, 'max_depth': 147, 'min_samples_split': 3, 'min_samples_leaf': 8}.
[I 2026-02-03 11:28:57,310] Trial 95 finished with values: [0.20863387296644662, 0.790282898220329] and parameters: {'n_estimators': 89, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 19}.
[I 2026-02-03 11:28:57,338] Trial 94 finished with values: [0.1503286226400144, 0.8486208258539168] and parameters: {'n_estimators': 117, 'max_depth': 53, 'min_samples_split': 16, 'min_samples_leaf': 8}.

c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:416: ExperimentalWarning: optuna.visualization.matplotlib._pareto_front.plot_pareto_front is experimental (supported from v2.8.0). The interface can change in the future.
  ax = vis.plot_pareto_front(study, target_names=target_names)
c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:425: ExperimentalWarning: optuna.visualization.matplotlib._optimization_history.plot_optimization_history is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_optimization_history(
c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:436: ExperimentalWarning: optuna.visualization.matplotlib._optimization_history.plot_optimization_history is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_optimization_history(
c:\Users\shakt\Documents\gitrepo\resource-allocation\core\armote_multi_output.py:447: ExperimentalWarning: optuna.visualization.matplotlib._param_importances.plot_param_importances is experimental (supported from v2.2.0). The interface can change in the future.
  ax = vis.plot_param_importances(study)

  Optuna plots for RFR saved in 'ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\plots' directory.
  Best model saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\models\RFR_best_model.pkl
  Y-Y plot saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\plots\RFR_yy_plot.png

--- Workflow Complete ---
✓ Results summary saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\results.csv
✓ Detailed results saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\results_detailed.txt
✓ Models saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\models
✓ Plots saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\plots
✓ Studies saved to: ground_truth_models/TiVNbMoHfTaW_Max_S_Max_TCond\studies
    Model  Optimization Time (s)  Retraining Time (s)  \
0  Linear                  0.000                0.001
1     RFR                 13.896                0.275

                                         Best Params Train R2 (Per-Output)  \
0                                                 {}      [0.7096, 0.5319]
1  {'n_estimators': 84, 'max_depth': 31, 'min_sam...      [0.9919, 0.9552]

  Train MSE (Per-Output) Train MAE (Per-Output) Test R2 (Per-Output)  \
0   [10.00024, 0.005514]    [2.23758, 0.059447]     [0.6969, 0.5537]
1   [0.278666, 0.000527]     [0.4066, 0.018603]     [0.9836, 0.8496]

   Test MSE (Per-Output) Test MAE (Per-Output)
0  [13.698718, 0.005524]    [2.594429, 0.0618]
1   [0.742405, 0.001862]  [0.648493, 0.034869]